// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: account_histories    Tools: 1
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/account_history",
      "pathParams": [],
      "queryParams": [
        "end_time",
        "start_time"
      ]
    },
    "description": "Get account historys",
    "input_schema": {
      "properties": {
        "end_time": {
          "description": "End_time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "start_time": {
          "description": "Start_time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        }
      },
      "required": [
        "end_time",
        "start_time"
      ],
      "type": "object"
    },
    "name": "list_account_histories",
    "tier": "readonly"
  }
];
