// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: agent_resource_types    Tools: 2
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/agent_resource_type/{agent_resource_type_id}",
      "pathParams": [
        "agent_resource_type_id"
      ],
      "queryParams": []
    },
    "description": "Get agent resource type",
    "input_schema": {
      "properties": {
        "agent_resource_type_id": {
          "description": "Agent resource type id",
          "type": "string"
        }
      },
      "required": [
        "agent_resource_type_id"
      ],
      "type": "object"
    },
    "name": "get_agent_resource_type",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/agent_resource_type",
      "pathParams": [],
      "queryParams": [
        "label",
        "resource_textkey",
        "platform",
        "category"
      ]
    },
    "description": "Get agent resource types",
    "input_schema": {
      "properties": {
        "category": {
          "description": "Filter results by category",
          "type": "string"
        },
        "label": {
          "description": "Filter results by label",
          "type": "string"
        },
        "platform": {
          "description": "Filter results by platform",
          "type": "string"
        },
        "resource_textkey": {
          "description": "Filter results by resource_textkey",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_agent_resource_types",
    "tier": "readonly"
  }
];
