// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: cloud_providers    Tools: 2
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_provider/{cloud_provider_id}",
      "pathParams": [
        "cloud_provider_id"
      ],
      "queryParams": []
    },
    "description": "Get cloud provider",
    "input_schema": {
      "properties": {
        "cloud_provider_id": {
          "description": "Cloud provider id",
          "type": "string"
        }
      },
      "required": [
        "cloud_provider_id"
      ],
      "type": "object"
    },
    "name": "get_cloud_provider",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_provider",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get cloud providers",
    "input_schema": {
      "type": "object"
    },
    "name": "list_cloud_providers",
    "tier": "readonly"
  }
];
