// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: cloud_credentials    Tools: 9
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/cloud_credential",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create cloud credential",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_cloud_credential",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/cloud_credential/{cloud_credential_id}/cloud_discovery",
      "pathParams": [
        "cloud_credential_id"
      ],
      "queryParams": []
    },
    "description": "Create cloud credential's cloud discovery",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "cloud_credential_id": {
          "description": "Cloud credential id",
          "type": "string"
        }
      },
      "required": [
        "cloud_credential_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_cloud_discovery",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_credential/{cloud_credential_id}",
      "pathParams": [
        "cloud_credential_id"
      ],
      "queryParams": []
    },
    "description": "Get cloud credential",
    "input_schema": {
      "properties": {
        "cloud_credential_id": {
          "description": "Cloud credential id",
          "type": "string"
        }
      },
      "required": [
        "cloud_credential_id"
      ],
      "type": "object"
    },
    "name": "get_cloud_credential",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_credential/{cloud_credential_id}/cloud_discovery/{cloud_discovery_id}",
      "pathParams": [
        "cloud_credential_id",
        "cloud_discovery_id"
      ],
      "queryParams": []
    },
    "description": "Get cloud credential's cloud discovery",
    "input_schema": {
      "properties": {
        "cloud_credential_id": {
          "description": "Cloud credential id",
          "type": "string"
        },
        "cloud_discovery_id": {
          "description": "Cloud discovery id",
          "type": "string"
        }
      },
      "required": [
        "cloud_credential_id",
        "cloud_discovery_id"
      ],
      "type": "object"
    },
    "name": "get_cloud_discovery",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_credential",
      "pathParams": [],
      "queryParams": [
        "cloud_provider"
      ]
    },
    "description": "Get cloud credentials",
    "input_schema": {
      "properties": {
        "cloud_provider": {
          "description": "Filter results by their provider",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_cloud_credentials",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_credential/{cloud_credential_id}/cloud_discovery",
      "pathParams": [
        "cloud_credential_id"
      ],
      "queryParams": []
    },
    "description": "Get cloud credential's cloud discoverys",
    "input_schema": {
      "properties": {
        "cloud_credential_id": {
          "description": "Cloud credential id",
          "type": "string"
        }
      },
      "required": [
        "cloud_credential_id"
      ],
      "type": "object"
    },
    "name": "list_cloud_discoveries",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/cloud_credential/{cloud_credential_id}",
      "pathParams": [
        "cloud_credential_id"
      ],
      "queryParams": []
    },
    "description": "Update cloud credential",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "cloud_credential_id": {
          "description": "Cloud credential id",
          "type": "string"
        }
      },
      "required": [
        "cloud_credential_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_cloud_credential",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/cloud_credential/{cloud_credential_id}/cloud_discovery/{cloud_discovery_id}",
      "pathParams": [
        "cloud_credential_id",
        "cloud_discovery_id"
      ],
      "queryParams": []
    },
    "description": "Update cloud credential's cloud discovery",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "cloud_credential_id": {
          "description": "Cloud credential id",
          "type": "string"
        },
        "cloud_discovery_id": {
          "description": "Cloud discovery id",
          "type": "string"
        }
      },
      "required": [
        "cloud_credential_id",
        "cloud_discovery_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_cloud_discovery",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "PUT",
      "path": "/cloud_credential/{cloud_credential_id}/run",
      "pathParams": [
        "cloud_credential_id"
      ],
      "queryParams": []
    },
    "description": "Run a discovery on the credential",
    "input_schema": {
      "properties": {
        "cloud_credential_id": {
          "description": "Cloud credential id",
          "type": "string"
        }
      },
      "required": [
        "cloud_credential_id"
      ],
      "type": "object"
    },
    "name": "update_run",
    "tier": "readwrite"
  }
];
