// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: cloud_services    Tools: 2
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_service/{cloud_service_id}",
      "pathParams": [
        "cloud_service_id"
      ],
      "queryParams": []
    },
    "description": "Get cloud service",
    "input_schema": {
      "properties": {
        "cloud_service_id": {
          "description": "Cloud service id",
          "type": "string"
        }
      },
      "required": [
        "cloud_service_id"
      ],
      "type": "object"
    },
    "name": "get_cloud_service",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_service",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get cloud services",
    "input_schema": {
      "type": "object"
    },
    "name": "list_cloud_services",
    "tier": "readonly"
  }
];
