// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: cloud_regions    Tools: 2
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_region/{cloud_region_id}",
      "pathParams": [
        "cloud_region_id"
      ],
      "queryParams": []
    },
    "description": "Get cloud region",
    "input_schema": {
      "properties": {
        "cloud_region_id": {
          "description": "Cloud region id",
          "type": "string"
        }
      },
      "required": [
        "cloud_region_id"
      ],
      "type": "object"
    },
    "name": "get_cloud_region",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/cloud_region",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get cloud regions",
    "input_schema": {
      "type": "object"
    },
    "name": "list_cloud_regions",
    "tier": "readonly"
  }
];
