// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: compound_services    Tools: 12
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/compound_service",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create compound service",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_compound_service",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/compound_service/{compound_service_id}",
      "pathParams": [
        "compound_service_id"
      ],
      "queryParams": []
    },
    "description": "Delete compound service",
    "input_schema": {
      "properties": {
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id"
      ],
      "type": "object"
    },
    "name": "delete_compound_service",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service/{compound_service_id}",
      "pathParams": [
        "compound_service_id"
      ],
      "queryParams": []
    },
    "description": "Get compound service",
    "input_schema": {
      "properties": {
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id"
      ],
      "type": "object"
    },
    "name": "get_compound_service",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service/{compound_service_id}/agent_resource_threshold/{agent_resource_threshold_id}",
      "pathParams": [
        "compound_service_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Get compound service's agent resource threshold",
    "input_schema": {
      "properties": {
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id",
        "agent_resource_threshold_id"
      ],
      "type": "object"
    },
    "name": "get_compound_service_agent_resource_threshold",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service/{compound_service_id}/network_service/{network_service_id}",
      "pathParams": [
        "compound_service_id",
        "network_service_id"
      ],
      "queryParams": []
    },
    "description": "Get compound service's network service",
    "input_schema": {
      "properties": {
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id",
        "network_service_id"
      ],
      "type": "object"
    },
    "name": "get_compound_service_network_service",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service/{compound_service_id}/network_service/{network_service_id}/response_time/{timescale}",
      "pathParams": [
        "compound_service_id",
        "network_service_id",
        "timescale"
      ],
      "queryParams": [
        "end_time"
      ]
    },
    "description": "Get service response time graph data",
    "input_schema": {
      "properties": {
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        },
        "end_time": {
          "description": "End time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "timescale": {
          "description": "('hour', 'day', 'week', 'month', or 'year')",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id",
        "network_service_id",
        "timescale"
      ],
      "type": "object"
    },
    "name": "get_compound_service_network_service_response_time",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service/{compound_service_id}/agent_resource_threshold",
      "pathParams": [
        "compound_service_id"
      ],
      "queryParams": []
    },
    "description": "Get compound service's agent resource thresholds",
    "input_schema": {
      "properties": {
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id"
      ],
      "type": "object"
    },
    "name": "list_compound_service_agent_resource_thresholds",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service/{compound_service_id}/availability",
      "pathParams": [
        "compound_service_id"
      ],
      "queryParams": [
        "start_time",
        "end_time"
      ]
    },
    "description": "Get compound service availability",
    "input_schema": {
      "properties": {
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        },
        "end_time": {
          "description": "End time of the range; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "start_time": {
          "description": "Start time of the range; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id",
        "start_time",
        "end_time"
      ],
      "type": "object"
    },
    "name": "list_compound_service_availabilities",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service/{compound_service_id}/network_service",
      "pathParams": [
        "compound_service_id"
      ],
      "queryParams": [
        "name",
        "service_type",
        "server_interface",
        "status",
        "tags",
        "monitoring_location"
      ]
    },
    "description": "Get compound service's network services",
    "input_schema": {
      "properties": {
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        },
        "monitoring_location": {
          "description": "Filter results by monitoring location URL either server (https://api2.panopta.com/v2/server/{server_id}), appliance (https://api2.panopta.com/v2/onsight/{onsight_id}), or monitor node (https://api2.panopta.com/v2/monitoring_node/{monitoring_node_id})",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_interface": {
          "description": "Filter results by server_interface",
          "type": "string"
        },
        "service_type": {
          "description": "Filter results by service_type id",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "suspended"
          ],
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id"
      ],
      "type": "object"
    },
    "name": "list_compound_service_network_services",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service/{compound_service_id}/outage",
      "pathParams": [
        "compound_service_id"
      ],
      "queryParams": [
        "end_time",
        "start_time",
        "status",
        "min_duration"
      ]
    },
    "description": "Get compound service's outages",
    "input_schema": {
      "properties": {
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        },
        "end_time": {
          "description": "End_time in UTC",
          "type": "string"
        },
        "min_duration": {
          "description": "Minimum outage duration in seconds",
          "type": "string"
        },
        "start_time": {
          "description": "Start_time in UTC",
          "type": "string"
        },
        "status": {
          "enum": [
            "active",
            "resolved"
          ],
          "type": "string"
        }
      },
      "required": [
        "compound_service_id"
      ],
      "type": "object"
    },
    "name": "list_compound_service_outages",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/compound_service",
      "pathParams": [],
      "queryParams": [
        "name",
        "tags"
      ]
    },
    "description": "Get compound services",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_compound_services",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/compound_service/{compound_service_id}",
      "pathParams": [
        "compound_service_id"
      ],
      "queryParams": []
    },
    "description": "Update compound service",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "compound_service_id": {
          "description": "Compound service id",
          "type": "string"
        }
      },
      "required": [
        "compound_service_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_compound_service",
    "tier": "readwrite"
  }
];
