// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: contact_groups    Tools: 5
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/contact_group",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create contact group",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_contact_group",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/contact_group/{contact_group_id}",
      "pathParams": [
        "contact_group_id"
      ],
      "queryParams": []
    },
    "description": "Delete contact group",
    "input_schema": {
      "properties": {
        "contact_group_id": {
          "description": "Contact group id",
          "type": "string"
        }
      },
      "required": [
        "contact_group_id"
      ],
      "type": "object"
    },
    "name": "delete_contact_group",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/contact_group/{contact_group_id}",
      "pathParams": [
        "contact_group_id"
      ],
      "queryParams": []
    },
    "description": "Get contact group",
    "input_schema": {
      "properties": {
        "contact_group_id": {
          "description": "Contact group id",
          "type": "string"
        }
      },
      "required": [
        "contact_group_id"
      ],
      "type": "object"
    },
    "name": "get_contact_group",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/contact_group",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get contact groups",
    "input_schema": {
      "type": "object"
    },
    "name": "list_contact_groups",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/contact_group/{contact_group_id}",
      "pathParams": [
        "contact_group_id"
      ],
      "queryParams": []
    },
    "description": "Update contact group",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "contact_group_id": {
          "description": "Contact group id",
          "type": "string"
        }
      },
      "required": [
        "contact_group_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_contact_group",
    "tier": "readwrite"
  }
];
