// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: contact_types    Tools: 2
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/contact_type/{contact_type_id}",
      "pathParams": [
        "contact_type_id"
      ],
      "queryParams": []
    },
    "description": "Get contact type",
    "input_schema": {
      "properties": {
        "contact_type_id": {
          "description": "Contact type id",
          "type": "string"
        }
      },
      "required": [
        "contact_type_id"
      ],
      "type": "object"
    },
    "name": "get_contact_type",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/contact_type",
      "pathParams": [],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get contact types",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_contact_types",
    "tier": "readonly"
  }
];
