// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: contacts    Tools: 11
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/contact",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create contact",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_contact",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/contact/{contact_id}/contact_info",
      "pathParams": [
        "contact_id"
      ],
      "queryParams": []
    },
    "description": "Create contact's contact info",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        }
      },
      "required": [
        "contact_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_contact_info",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/contact/{contact_id}",
      "pathParams": [
        "contact_id"
      ],
      "queryParams": []
    },
    "description": "Delete contact",
    "input_schema": {
      "properties": {
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        }
      },
      "required": [
        "contact_id"
      ],
      "type": "object"
    },
    "name": "delete_contact",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/contact/{contact_id}/contact_info/{contact_info_id}",
      "pathParams": [
        "contact_id",
        "contact_info_id"
      ],
      "queryParams": []
    },
    "description": "Delete contact's contact info",
    "input_schema": {
      "properties": {
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        },
        "contact_info_id": {
          "description": "Contact info id",
          "type": "string"
        }
      },
      "required": [
        "contact_id",
        "contact_info_id"
      ],
      "type": "object"
    },
    "name": "delete_contact_info",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/contact/{contact_id}",
      "pathParams": [
        "contact_id"
      ],
      "queryParams": []
    },
    "description": "Get contact",
    "input_schema": {
      "properties": {
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        }
      },
      "required": [
        "contact_id"
      ],
      "type": "object"
    },
    "name": "get_contact",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/contact/{contact_id}/contact_info/{contact_info_id}",
      "pathParams": [
        "contact_id",
        "contact_info_id"
      ],
      "queryParams": []
    },
    "description": "Get contact's contact info",
    "input_schema": {
      "properties": {
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        },
        "contact_info_id": {
          "description": "Contact info id",
          "type": "string"
        }
      },
      "required": [
        "contact_id",
        "contact_info_id"
      ],
      "type": "object"
    },
    "name": "get_contact_info",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/contact/{contact_id}/contact_info",
      "pathParams": [
        "contact_id"
      ],
      "queryParams": []
    },
    "description": "Get contact's contact infos",
    "input_schema": {
      "properties": {
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        }
      },
      "required": [
        "contact_id"
      ],
      "type": "object"
    },
    "name": "list_contact_infos",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/contact",
      "pathParams": [],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get contacts",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_contacts",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/contact/{contact_id}/contact_info/{contact_info_id}",
      "pathParams": [
        "contact_id",
        "contact_info_id"
      ],
      "queryParams": []
    },
    "description": "Create contact's contact info",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        },
        "contact_info_id": {
          "description": "Contact info id",
          "type": "string"
        }
      },
      "required": [
        "contact_id",
        "contact_info_id",
        "body"
      ],
      "type": "object"
    },
    "name": "replace_contact_info",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/contact/{contact_id}",
      "pathParams": [
        "contact_id"
      ],
      "queryParams": []
    },
    "description": "Update contact",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        }
      },
      "required": [
        "contact_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_contact",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/contact/{contact_id}/contact_info/{contact_info_id}",
      "pathParams": [
        "contact_id",
        "contact_info_id"
      ],
      "queryParams": []
    },
    "description": "Update contact's contact info",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "contact_id": {
          "description": "Contact id",
          "type": "string"
        },
        "contact_info_id": {
          "description": "Contact info id",
          "type": "string"
        }
      },
      "required": [
        "contact_id",
        "contact_info_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_contact_info",
    "tier": "readwrite"
  }
];
