// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: dashboards    Tools: 5
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/dashboard",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create dashboard",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_dashboard",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/dashboard/{dashboard_id}",
      "pathParams": [
        "dashboard_id"
      ],
      "queryParams": []
    },
    "description": "Delete dashboard",
    "input_schema": {
      "properties": {
        "dashboard_id": {
          "description": "Dashboard id",
          "type": "string"
        }
      },
      "required": [
        "dashboard_id"
      ],
      "type": "object"
    },
    "name": "delete_dashboard",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/dashboard/{dashboard_id}",
      "pathParams": [
        "dashboard_id"
      ],
      "queryParams": []
    },
    "description": "Get dashboard",
    "input_schema": {
      "properties": {
        "dashboard_id": {
          "description": "Dashboard id",
          "type": "string"
        }
      },
      "required": [
        "dashboard_id"
      ],
      "type": "object"
    },
    "name": "get_dashboard",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/dashboard",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get dashboards",
    "input_schema": {
      "type": "object"
    },
    "name": "list_dashboards",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/dashboard/{dashboard_id}",
      "pathParams": [
        "dashboard_id"
      ],
      "queryParams": []
    },
    "description": "Update dashboard",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "dashboard_id": {
          "description": "Dashboard id",
          "type": "string"
        }
      },
      "required": [
        "dashboard_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_dashboard",
    "tier": "readwrite"
  }
];
