// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: dem_applications    Tools: 10
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/dem_application",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create dem application",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_dem_application",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/dem_application/{dem_application_id}/instance",
      "pathParams": [
        "dem_application_id"
      ],
      "queryParams": []
    },
    "description": "Add dem template instance",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "dem_application_id": {
          "description": "Dem application id",
          "type": "string"
        }
      },
      "required": [
        "dem_application_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_instance",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/dem_application/{dem_application_id}",
      "pathParams": [
        "dem_application_id"
      ],
      "queryParams": []
    },
    "description": "Delete dem application",
    "input_schema": {
      "properties": {
        "dem_application_id": {
          "description": "Dem application id",
          "type": "string"
        }
      },
      "required": [
        "dem_application_id"
      ],
      "type": "object"
    },
    "name": "delete_dem_application",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/dem_application/{dem_application_id}",
      "pathParams": [
        "dem_application_id"
      ],
      "queryParams": []
    },
    "description": "Get dem application",
    "input_schema": {
      "properties": {
        "dem_application_id": {
          "description": "Dem application id",
          "type": "string"
        }
      },
      "required": [
        "dem_application_id"
      ],
      "type": "object"
    },
    "name": "get_dem_application",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/dem_application",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get dem applications",
    "input_schema": {
      "type": "object"
    },
    "name": "list_dem_applications",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/dem_application/{dem_application_id}/instance",
      "pathParams": [
        "dem_application_id"
      ],
      "queryParams": [
        "fqdn",
        "name",
        "tags",
        "notification_schedule"
      ]
    },
    "description": "Add dem template instance",
    "input_schema": {
      "properties": {
        "dem_application_id": {
          "description": "Dem application id",
          "type": "string"
        },
        "fqdn": {
          "description": "Fqdn of the template, should not be empty",
          "type": "string"
        },
        "name": {
          "description": "Name of the template, should not be empty",
          "type": "string"
        },
        "notification_schedule": {
          "description": "URL to a NotificationSchedule that will be used for the application; Url format = https://api2.panopta.com/v2/notification_schedule/{notification_schedule_id}",
          "type": "string"
        },
        "tags": {
          "description": "Tags of the template instance",
          "type": "string"
        }
      },
      "required": [
        "dem_application_id"
      ],
      "type": "object"
    },
    "name": "list_instances",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/dem_application/{dem_application_id}/location",
      "pathParams": [
        "dem_application_id"
      ],
      "queryParams": [
        "endpoint_agent",
        "public_probes",
        "onsight",
        "sdwan_device",
        "add_replace",
        "type_filter"
      ]
    },
    "description": "Dem monitoring location",
    "input_schema": {
      "properties": {
        "add_replace": {
          "description": "Pass 'add' as an option to either add the monitoring location(s) or pass 'replace' to completely replace the existing monitoring location(s). This might take effect in a few minutes. If nothing is passed, 'add' will be used as a default.",
          "type": "string"
        },
        "dem_application_id": {
          "description": "Dem application id",
          "type": "string"
        },
        "endpoint_agent": {
          "description": " Url format = https://api2.panopta.com/v2/server/{server_id}",
          "type": "string"
        },
        "onsight": {
          "description": " Url format = https://api2.panopta.com/v2/onsight/{onsight_id}",
          "type": "string"
        },
        "public_probes": {
          "description": " Url format = https://api2.panopta.com/v2/monitoring_node/{monitoring_node_id}",
          "type": "string"
        },
        "sdwan_device": {
          "description": " Url format = https://api2.panopta.com/v2/server/{server_id}",
          "type": "string"
        },
        "type_filter": {
          "description": "Filter GET results by monitoring location type",
          "enum": [
            "endpoint_agent",
            "public_probes",
            "onsight",
            "sdwan_device"
          ],
          "type": "string"
        }
      },
      "required": [
        "dem_application_id"
      ],
      "type": "object"
    },
    "name": "list_locations",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/dem_application/{dem_application_id}",
      "pathParams": [
        "dem_application_id"
      ],
      "queryParams": []
    },
    "description": "Update dem application",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "dem_application_id": {
          "description": "Dem application id",
          "type": "string"
        }
      },
      "required": [
        "dem_application_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_dem_application",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/dem_application/{dem_application_id}/location",
      "pathParams": [
        "dem_application_id"
      ],
      "queryParams": []
    },
    "description": "Dem monitoring location",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "dem_application_id": {
          "description": "Dem application id",
          "type": "string"
        }
      },
      "required": [
        "dem_application_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_location",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/dem_application/{dem_application_id}/instance/{server_template_id}/path_monitoring",
      "pathParams": [
        "dem_application_id",
        "server_template_id"
      ],
      "queryParams": []
    },
    "description": "Set path monitoring",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "dem_application_id": {
          "description": "Dem application id",
          "type": "string"
        },
        "server_template_id": {
          "description": "Server template id",
          "type": "string"
        }
      },
      "required": [
        "dem_application_id",
        "server_template_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_path_monitoring",
    "tier": "readwrite"
  }
];
