// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: fabric_connections    Tools: 4
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/fabric_connection",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create fabric connection",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_fabric_connection",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/fabric_connection/{fabric_connection_id}",
      "pathParams": [
        "fabric_connection_id"
      ],
      "queryParams": []
    },
    "description": "Delete fabric connection",
    "input_schema": {
      "properties": {
        "fabric_connection_id": {
          "description": "Fabric connection id",
          "type": "string"
        }
      },
      "required": [
        "fabric_connection_id"
      ],
      "type": "object"
    },
    "name": "delete_fabric_connection",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/fabric_connection/{fabric_connection_id}",
      "pathParams": [
        "fabric_connection_id"
      ],
      "queryParams": []
    },
    "description": "Get fabric connection",
    "input_schema": {
      "properties": {
        "fabric_connection_id": {
          "description": "Fabric connection id",
          "type": "string"
        }
      },
      "required": [
        "fabric_connection_id"
      ],
      "type": "object"
    },
    "name": "get_fabric_connection",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/fabric_connection",
      "pathParams": [],
      "queryParams": [
        "status"
      ]
    },
    "description": "Get fabric connections",
    "input_schema": {
      "properties": {
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "disabled",
            "deleted",
            "error"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_fabric_connections",
    "tier": "readonly"
  }
];
