// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Re-exports every codegen domain module under a stable name.

import { TOOLS as accountHistoriesTools } from './account_histories.js';
import { TOOLS as agentResourceTypesTools } from './agent_resource_types.js';
import { TOOLS as cloudCredentialsTools } from './cloud_credentials.js';
import { TOOLS as cloudProvidersTools } from './cloud_providers.js';
import { TOOLS as cloudRegionsTools } from './cloud_regions.js';
import { TOOLS as cloudServicesTools } from './cloud_services.js';
import { TOOLS as compoundServicesTools } from './compound_services.js';
import { TOOLS as contactGroupsTools } from './contact_groups.js';
import { TOOLS as contactTypesTools } from './contact_types.js';
import { TOOLS as contactsTools } from './contacts.js';
import { TOOLS as dashboardsTools } from './dashboards.js';
import { TOOLS as demApplicationsTools } from './dem_applications.js';
import { TOOLS as fabricConnectionsTools } from './fabric_connections.js';
import { TOOLS as historicalOutagesTools } from './historical_outages.js';
import { TOOLS as maintenanceSchedulesTools } from './maintenance_schedules.js';
import { TOOLS as monitoringNodesTools } from './monitoring_nodes.js';
import { TOOLS as networkServiceTypesTools } from './network_service_types.js';
import { TOOLS as notificationSchedulesTools } from './notification_schedules.js';
import { TOOLS as onsightGroupsTools } from './onsight_groups.js';
import { TOOLS as onsightsTools } from './onsights.js';
import { TOOLS as outagesTools } from './outages.js';
import { TOOLS as prometheusResourcesTools } from './prometheus_resources.js';
import { TOOLS as publicsTools } from './publics.js';
import { TOOLS as rolesTools } from './roles.js';
import { TOOLS as rotatingContactsTools } from './rotating_contacts.js';
import { TOOLS as serverAttributeTypesTools } from './server_attribute_types.js';
import { TOOLS as serverGroupsTools } from './server_groups.js';
import { TOOLS as serverTemplatesTools } from './server_templates.js';
import { TOOLS as serversTools } from './servers.js';
import { TOOLS as snmpCredentialsTools } from './snmp_credentials.js';
import { TOOLS as statusPagesTools } from './status_pages.js';
import { TOOLS as timezonesTools } from './timezones.js';
import { TOOLS as usersTools } from './users.js';

export const ALL_CODEGEN_TOOLS = [
  ...accountHistoriesTools,
  ...agentResourceTypesTools,
  ...cloudCredentialsTools,
  ...cloudProvidersTools,
  ...cloudRegionsTools,
  ...cloudServicesTools,
  ...compoundServicesTools,
  ...contactGroupsTools,
  ...contactTypesTools,
  ...contactsTools,
  ...dashboardsTools,
  ...demApplicationsTools,
  ...fabricConnectionsTools,
  ...historicalOutagesTools,
  ...maintenanceSchedulesTools,
  ...monitoringNodesTools,
  ...networkServiceTypesTools,
  ...notificationSchedulesTools,
  ...onsightGroupsTools,
  ...onsightsTools,
  ...outagesTools,
  ...prometheusResourcesTools,
  ...publicsTools,
  ...rolesTools,
  ...rotatingContactsTools,
  ...serverAttributeTypesTools,
  ...serverGroupsTools,
  ...serverTemplatesTools,
  ...serversTools,
  ...snmpCredentialsTools,
  ...statusPagesTools,
  ...timezonesTools,
  ...usersTools,
];
