// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: maintenance_schedules    Tools: 11
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/maintenance_schedule",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create maintenance schedule",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_maintenance_schedule",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/maintenance_schedule/{maintenance_schedule_id}",
      "pathParams": [
        "maintenance_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Delete maintenance schedule",
    "input_schema": {
      "properties": {
        "maintenance_schedule_id": {
          "description": "Maintenance schedule id",
          "type": "string"
        }
      },
      "required": [
        "maintenance_schedule_id"
      ],
      "type": "object"
    },
    "name": "delete_maintenance_schedule",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/maintenance_schedule/{maintenance_schedule_id}",
      "pathParams": [
        "maintenance_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Get maintenance schedule",
    "input_schema": {
      "properties": {
        "maintenance_schedule_id": {
          "description": "Maintenance schedule id",
          "type": "string"
        }
      },
      "required": [
        "maintenance_schedule_id"
      ],
      "type": "object"
    },
    "name": "get_maintenance_schedule",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/maintenance_schedule/active_or_pending",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get active or pending maintenance schedules",
    "input_schema": {
      "type": "object"
    },
    "name": "list_active_or_pendings",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/maintenance_schedule/active",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get active maintenance schedules",
    "input_schema": {
      "type": "object"
    },
    "name": "list_actives",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/maintenance_schedule",
      "pathParams": [],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get maintenance schedules",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_maintenance_schedules",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/maintenance_schedule/{maintenance_schedule_id}/extend/{num_minutes}",
      "pathParams": [
        "maintenance_schedule_id",
        "num_minutes"
      ],
      "queryParams": []
    },
    "description": "Extend maintenance schedule",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "maintenance_schedule_id": {
          "description": "Maintenance schedule id",
          "type": "string"
        },
        "num_minutes": {
          "description": "Num minutes",
          "type": "string"
        }
      },
      "required": [
        "maintenance_schedule_id",
        "num_minutes",
        "body"
      ],
      "type": "object"
    },
    "name": "update_extend",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/maintenance_schedule/{maintenance_schedule_id}",
      "pathParams": [
        "maintenance_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Update maintenance schedule",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "maintenance_schedule_id": {
          "description": "Maintenance schedule id",
          "type": "string"
        }
      },
      "required": [
        "maintenance_schedule_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_maintenance_schedule",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/maintenance_schedule/{maintenance_schedule_id}/pause",
      "pathParams": [
        "maintenance_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Pause maintenance schedule",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "maintenance_schedule_id": {
          "description": "Maintenance schedule id",
          "type": "string"
        }
      },
      "required": [
        "maintenance_schedule_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_pause",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/maintenance_schedule/{maintenance_schedule_id}/resume",
      "pathParams": [
        "maintenance_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Resume maintenance schedule",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "maintenance_schedule_id": {
          "description": "Maintenance schedule id",
          "type": "string"
        }
      },
      "required": [
        "maintenance_schedule_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_resume",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/maintenance_schedule/{maintenance_schedule_id}/terminate",
      "pathParams": [
        "maintenance_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Terminate maintenance schedule",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "maintenance_schedule_id": {
          "description": "Maintenance schedule id",
          "type": "string"
        }
      },
      "required": [
        "maintenance_schedule_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_terminate",
    "tier": "readwrite"
  }
];
