// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: monitoring_nodes    Tools: 2
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/monitoring_node/{monitoring_node_id}",
      "pathParams": [
        "monitoring_node_id"
      ],
      "queryParams": []
    },
    "description": "Get monitoring node",
    "input_schema": {
      "properties": {
        "monitoring_node_id": {
          "description": "Monitoring node id",
          "type": "string"
        }
      },
      "required": [
        "monitoring_node_id"
      ],
      "type": "object"
    },
    "name": "get_monitoring_node",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/monitoring_node",
      "pathParams": [],
      "queryParams": [
        "name",
        "hostname",
        "ip_address"
      ]
    },
    "description": "Get monitoring nodes",
    "input_schema": {
      "properties": {
        "hostname": {
          "description": "Filter results by hostname",
          "type": "string"
        },
        "ip_address": {
          "description": "Filter results by ip_address",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_monitoring_nodes",
    "tier": "readonly"
  }
];
