// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: network_service_types    Tools: 3
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/network_service_type/{network_service_type_id}",
      "pathParams": [
        "network_service_type_id"
      ],
      "queryParams": []
    },
    "description": "Get network service type",
    "input_schema": {
      "properties": {
        "network_service_type_id": {
          "description": "Network service type id",
          "type": "string"
        }
      },
      "required": [
        "network_service_type_id"
      ],
      "type": "object"
    },
    "name": "get_network_service_type",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/network_service_type/{network_service_type_id}/option/{option_id}",
      "pathParams": [
        "network_service_type_id",
        "option_id"
      ],
      "queryParams": []
    },
    "description": "Get network service type's option",
    "input_schema": {
      "properties": {
        "network_service_type_id": {
          "description": "Network service type id",
          "type": "string"
        },
        "option_id": {
          "description": "Option id",
          "type": "string"
        }
      },
      "required": [
        "network_service_type_id",
        "option_id"
      ],
      "type": "object"
    },
    "name": "get_option",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/network_service_type",
      "pathParams": [],
      "queryParams": [
        "name",
        "textkey",
        "service_class"
      ]
    },
    "description": "Get network service types",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "service_class": {
          "description": "Filter results by service_class",
          "type": "string"
        },
        "textkey": {
          "description": "Filter results by textkey",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_network_service_types",
    "tier": "readonly"
  }
];
