// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: notification_schedules    Tools: 10
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/notification_schedule",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create notification schedule",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_notification_schedule",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/notification_schedule/{notification_schedule_id}",
      "pathParams": [
        "notification_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Delete notification schedule",
    "input_schema": {
      "properties": {
        "notification_schedule_id": {
          "description": "Notification schedule id",
          "type": "string"
        }
      },
      "required": [
        "notification_schedule_id"
      ],
      "type": "object"
    },
    "name": "delete_notification_schedule",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/notification_schedule/{notification_schedule_id}",
      "pathParams": [
        "notification_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Get notification schedule",
    "input_schema": {
      "properties": {
        "notification_schedule_id": {
          "description": "Notification schedule id",
          "type": "string"
        }
      },
      "required": [
        "notification_schedule_id"
      ],
      "type": "object"
    },
    "name": "get_notification_schedule",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/notification_schedule/{notification_schedule_id}/agent_resource_threshold",
      "pathParams": [
        "notification_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Get notification schedule's agent resource thresholds",
    "input_schema": {
      "properties": {
        "notification_schedule_id": {
          "description": "Notification schedule id",
          "type": "string"
        }
      },
      "required": [
        "notification_schedule_id"
      ],
      "type": "object"
    },
    "name": "list_notification_schedule_agent_resource_thresholds",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/notification_schedule/{notification_schedule_id}/compound_service",
      "pathParams": [
        "notification_schedule_id"
      ],
      "queryParams": [
        "name",
        "tags"
      ]
    },
    "description": "Get notification schedule's compound services",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "notification_schedule_id": {
          "description": "Notification schedule id",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "notification_schedule_id"
      ],
      "type": "object"
    },
    "name": "list_notification_schedule_compound_services",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/notification_schedule/{notification_schedule_id}/network_service",
      "pathParams": [
        "notification_schedule_id"
      ],
      "queryParams": [
        "name",
        "service_type",
        "server_interface",
        "status",
        "tags",
        "monitoring_location"
      ]
    },
    "description": "Get notification schedule's network services",
    "input_schema": {
      "properties": {
        "monitoring_location": {
          "description": "Filter results by monitoring location URL either server (https://api2.panopta.com/v2/server/{server_id}), appliance (https://api2.panopta.com/v2/onsight/{onsight_id}), or monitor node (https://api2.panopta.com/v2/monitoring_node/{monitoring_node_id})",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "notification_schedule_id": {
          "description": "Notification schedule id",
          "type": "string"
        },
        "server_interface": {
          "description": "Filter results by server_interface",
          "type": "string"
        },
        "service_type": {
          "description": "Filter results by service_type id",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "suspended"
          ],
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "notification_schedule_id"
      ],
      "type": "object"
    },
    "name": "list_notification_schedule_network_services",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/notification_schedule/{notification_schedule_id}/server_group",
      "pathParams": [
        "notification_schedule_id"
      ],
      "queryParams": [
        "name",
        "tags",
        "root_only"
      ]
    },
    "description": "Get notification schedule's server groups",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "notification_schedule_id": {
          "description": "Notification schedule id",
          "type": "string"
        },
        "root_only": {
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "notification_schedule_id"
      ],
      "type": "object"
    },
    "name": "list_notification_schedule_server_groups",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/notification_schedule/{notification_schedule_id}/server",
      "pathParams": [
        "notification_schedule_id"
      ],
      "queryParams": [
        "name",
        "fqdn",
        "server_key",
        "partner_server_id",
        "tags",
        "attributes",
        "server_group",
        "status"
      ]
    },
    "description": "Get notification schedule's servers",
    "input_schema": {
      "properties": {
        "attributes": {
          "description": "Filter results by attribute {name:value} pairs (comma separated)",
          "type": "string"
        },
        "fqdn": {
          "description": "Filter results by fqdn",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "notification_schedule_id": {
          "description": "Notification schedule id",
          "type": "string"
        },
        "partner_server_id": {
          "description": "Filter results by partner_server_id",
          "type": "string"
        },
        "server_group": {
          "description": "Filter results by server_group id",
          "type": "string"
        },
        "server_key": {
          "description": "Filter results by server_key",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "suspended",
            "deleted",
            "pending"
          ],
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "notification_schedule_id"
      ],
      "type": "object"
    },
    "name": "list_notification_schedule_servers",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/notification_schedule",
      "pathParams": [],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get notification schedules",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_notification_schedules",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/notification_schedule/{notification_schedule_id}",
      "pathParams": [
        "notification_schedule_id"
      ],
      "queryParams": []
    },
    "description": "Update notification schedule",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "notification_schedule_id": {
          "description": "Notification schedule id",
          "type": "string"
        }
      },
      "required": [
        "notification_schedule_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_notification_schedule",
    "tier": "readwrite"
  }
];
