// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: onsight_groups    Tools: 5
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/onsight_group",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create onsight group",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_onsight_group",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/onsight_group/{onsight_group_id}",
      "pathParams": [
        "onsight_group_id"
      ],
      "queryParams": []
    },
    "description": "Delete onsight group",
    "input_schema": {
      "properties": {
        "onsight_group_id": {
          "description": "Onsight group id",
          "type": "string"
        }
      },
      "required": [
        "onsight_group_id"
      ],
      "type": "object"
    },
    "name": "delete_onsight_group",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/onsight_group/{onsight_group_id}",
      "pathParams": [
        "onsight_group_id"
      ],
      "queryParams": []
    },
    "description": "Get onsight group",
    "input_schema": {
      "properties": {
        "onsight_group_id": {
          "description": "Onsight group id",
          "type": "string"
        }
      },
      "required": [
        "onsight_group_id"
      ],
      "type": "object"
    },
    "name": "get_onsight_group",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/onsight_group",
      "pathParams": [],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get onsight groups",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_onsight_groups",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/onsight_group/{onsight_group_id}",
      "pathParams": [
        "onsight_group_id"
      ],
      "queryParams": []
    },
    "description": "Update onsight group",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "onsight_group_id": {
          "description": "Onsight group id",
          "type": "string"
        }
      },
      "required": [
        "onsight_group_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_onsight_group",
    "tier": "readwrite"
  }
];
