// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: onsights    Tools: 8
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/onsight",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create onsight",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_onsight",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/onsight/{onsight_id}",
      "pathParams": [
        "onsight_id"
      ],
      "queryParams": []
    },
    "description": "Delete onsight",
    "input_schema": {
      "properties": {
        "onsight_id": {
          "description": "Onsight id",
          "type": "string"
        }
      },
      "required": [
        "onsight_id"
      ],
      "type": "object"
    },
    "name": "delete_onsight",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/onsight/{onsight_id}/countermeasure_metadata/{countermeasure_metadata_id}",
      "pathParams": [
        "onsight_id",
        "countermeasure_metadata_id"
      ],
      "queryParams": []
    },
    "description": "Get onsight's countermeasure metadata",
    "input_schema": {
      "properties": {
        "countermeasure_metadata_id": {
          "description": "Countermeasure metadata id",
          "type": "string"
        },
        "onsight_id": {
          "description": "Onsight id",
          "type": "string"
        }
      },
      "required": [
        "onsight_id",
        "countermeasure_metadata_id"
      ],
      "type": "object"
    },
    "name": "get_countermeasure_metadata",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/onsight/{onsight_id}",
      "pathParams": [
        "onsight_id"
      ],
      "queryParams": []
    },
    "description": "Get onsight",
    "input_schema": {
      "properties": {
        "onsight_id": {
          "description": "Onsight id",
          "type": "string"
        }
      },
      "required": [
        "onsight_id"
      ],
      "type": "object"
    },
    "name": "get_onsight",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/onsight/{onsight_id}/countermeasure_metadata",
      "pathParams": [
        "onsight_id"
      ],
      "queryParams": [
        "status"
      ]
    },
    "description": "Get onsight's countermeasure metadatas",
    "input_schema": {
      "properties": {
        "onsight_id": {
          "description": "Onsight id",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "pending",
            "available",
            "unavailable"
          ],
          "type": "string"
        }
      },
      "required": [
        "onsight_id"
      ],
      "type": "object"
    },
    "name": "list_countermeasure_metadatas",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/onsight",
      "pathParams": [],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get onsights",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_onsights",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/onsight/{onsight_id}/servers",
      "pathParams": [
        "onsight_id"
      ],
      "queryParams": []
    },
    "description": "OnSight discovered servers",
    "input_schema": {
      "properties": {
        "onsight_id": {
          "description": "Onsight id",
          "type": "string"
        }
      },
      "required": [
        "onsight_id"
      ],
      "type": "object"
    },
    "name": "list_serverses",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/onsight/{onsight_id}",
      "pathParams": [
        "onsight_id"
      ],
      "queryParams": []
    },
    "description": "Update onsight",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "onsight_id": {
          "description": "Onsight id",
          "type": "string"
        }
      },
      "required": [
        "onsight_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_onsight",
    "tier": "readwrite"
  }
];
