// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: outages    Tools: 27
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/outage/{outage_id}/outage_log",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": [
        "log_start_timestamp"
      ]
    },
    "description": "Create outage's outage log",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "log_start_timestamp": {
          "description": "Log start timestamp in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_outage_log",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/outage/{outage_id}/outage_metadata",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Create outage's outage metadata",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_outage_metadata",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": [
        "end_time",
        "start_time"
      ]
    },
    "description": "Get outage",
    "input_schema": {
      "properties": {
        "end_time": {
          "description": "End_time in UTC",
          "type": "string"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        },
        "start_time": {
          "description": "Start_time in UTC",
          "type": "string"
        }
      },
      "required": [
        "outage_id"
      ],
      "type": "object"
    },
    "name": "get_outage",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/delay/{delay_in_seconds}",
      "pathParams": [
        "outage_id",
        "delay_in_seconds"
      ],
      "queryParams": [
        "who"
      ]
    },
    "description": "Delay outage",
    "input_schema": {
      "properties": {
        "delay_in_seconds": {
          "description": "Delay in seconds; a value of 0 meaning permanently delay any future alerts",
          "type": "string"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        },
        "who": {
          "description": "Indicate who has acknowledged the alert; Url format = [https://api2.panopta.com/v2/user/{user_id} or https://api2.panopta.com/v2/contact/{contact_id}]",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "delay_in_seconds",
        "who"
      ],
      "type": "object"
    },
    "name": "get_outage_delay",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/actions",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Notification actions",
    "input_schema": {
      "properties": {
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id"
      ],
      "type": "object"
    },
    "name": "list_actionses",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/broadcast",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": [
        "message",
        "who"
      ]
    },
    "description": "Broadcast a message",
    "input_schema": {
      "properties": {
        "message": {
          "description": "Broadcast message",
          "type": "string"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        },
        "who": {
          "description": "Indicate who has boradcasted the alert message; Url format = [https://api2.panopta.com/v2/user/{user_id} or https://api2.panopta.com/v2/contact/{contact_id}]",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "message",
        "who"
      ],
      "type": "object"
    },
    "name": "list_broadcasts",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/countermeasure_output",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Countermeasure output",
    "input_schema": {
      "properties": {
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id"
      ],
      "type": "object"
    },
    "name": "list_countermeasure_outputs",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/acknowledge",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": [
        "who",
        "delay_in_seconds",
        "message",
        "should_broadcast"
      ]
    },
    "description": "Acknowledge outage",
    "input_schema": {
      "properties": {
        "delay_in_seconds": {
          "description": "Delay in seconds",
          "type": "string"
        },
        "message": {
          "description": "Broadcast message",
          "type": "string"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        },
        "should_broadcast": {
          "description": "Indicate that the message should be broadcasted",
          "type": "string"
        },
        "who": {
          "description": "Indicate who has acknowledged the alert; Url format = [https://api2.panopta.com/v2/user/{user_id} or https://api2.panopta.com/v2/contact/{contact_id}]",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "who"
      ],
      "type": "object"
    },
    "name": "list_outage_acknowledges",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/active",
      "pathParams": [],
      "queryParams": [
        "server_id"
      ]
    },
    "description": "Get active outages",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Filter active outages by server id.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_outage_actives",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/countermeasure_metadata",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Countermeasure metadata",
    "input_schema": {
      "properties": {
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id"
      ],
      "type": "object"
    },
    "name": "list_outage_countermeasure_metadatas",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/countermeasure",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": [
        "status"
      ]
    },
    "description": "Get outage's countermeasures",
    "input_schema": {
      "properties": {
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "type": "string"
        }
      },
      "required": [
        "outage_id"
      ],
      "type": "object"
    },
    "name": "list_outage_countermeasures",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/escalate",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": [
        "who"
      ]
    },
    "description": "Escalate outage",
    "input_schema": {
      "properties": {
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        },
        "who": {
          "description": "Indicate who has acknowledged the alert; Url format = [https://api2.panopta.com/v2/user/{user_id} or https://api2.panopta.com/v2/contact/{contact_id}]",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "who"
      ],
      "type": "object"
    },
    "name": "list_outage_escalates",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/outage_log",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": [
        "log_start_timestamp"
      ]
    },
    "description": "Get outage's outage logs",
    "input_schema": {
      "properties": {
        "log_start_timestamp": {
          "description": "Log start timestamp in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id"
      ],
      "type": "object"
    },
    "name": "list_outage_logs",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/outage_metadata",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Get outage's outage metadatas",
    "input_schema": {
      "properties": {
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id"
      ],
      "type": "object"
    },
    "name": "list_outage_metadatas",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage",
      "pathParams": [],
      "queryParams": [
        "server",
        "severity",
        "status",
        "end_time",
        "start_time"
      ]
    },
    "description": "Get outages",
    "input_schema": {
      "properties": {
        "end_time": {
          "description": "End_time in UTC",
          "type": "string"
        },
        "server": {
          "description": "Filter results by server id",
          "type": "string"
        },
        "severity": {
          "description": "Filter results by severity",
          "enum": [
            "critical",
            "warning"
          ],
          "type": "string"
        },
        "start_time": {
          "description": "Start_time in UTC",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "resolved"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_outages",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/{outage_id}/preoutage_graph",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": [
        "timescale"
      ]
    },
    "description": "Preoutage graph",
    "input_schema": {
      "properties": {
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        },
        "timescale": {
          "description": "Graph timescale (defaults to hour)",
          "enum": [
            "hour",
            "day",
            "week",
            "month",
            "year"
          ],
          "type": "string"
        }
      },
      "required": [
        "outage_id"
      ],
      "type": "object"
    },
    "name": "list_preoutage_graphs",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/outage/resolved",
      "pathParams": [],
      "queryParams": [
        "end_time",
        "start_time",
        "min_duration"
      ]
    },
    "description": "Get resolved outages",
    "input_schema": {
      "properties": {
        "end_time": {
          "description": "End time of the range in UTC",
          "type": "string"
        },
        "min_duration": {
          "description": "Minimum outage duration in seconds",
          "type": "string"
        },
        "start_time": {
          "description": "Start time of the range in UTC",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_resolveds",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/broadcast",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Broadcast a message",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_broadcast",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/description",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Update description of a custom incident",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_description",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/force_resolve",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Force resolution of a manual incident",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_force_resolve",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/lead",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Lead on the outage",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_lead",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/acknowledge",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Acknowledge outage",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_outage_acknowledge",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/countermeasure",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Update outage's countermeasure",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_outage_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/delay/{delay_in_seconds}",
      "pathParams": [
        "outage_id",
        "delay_in_seconds"
      ],
      "queryParams": []
    },
    "description": "Delay outage",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "delay_in_seconds": {
          "description": "Delay in seconds; a value of 0 meaning permanently delay any future alerts",
          "type": "string"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "delay_in_seconds",
        "body"
      ],
      "type": "object"
    },
    "name": "update_outage_delay",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/escalate",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Escalate outage",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_outage_escalate",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/summary",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Add a summary for your outage",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_summary",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/outage/{outage_id}/tags",
      "pathParams": [
        "outage_id"
      ],
      "queryParams": []
    },
    "description": "Set tags for the incident",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "outage_id": {
          "description": "Outage id",
          "type": "string"
        }
      },
      "required": [
        "outage_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_tags",
    "tier": "readwrite"
  }
];
