// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: prometheus_resources    Tools: 1
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "POST",
      "path": "/prometheus_resource",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create prometheus resource",
    "input_schema": {
      "type": "object"
    },
    "name": "create_prometheus_resource",
    "tier": "readwrite"
  }
];
