// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: publics    Tools: 6
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/public/outage/{HASH}/delay/{delay_in_seconds}",
      "pathParams": [
        "HASH",
        "delay_in_seconds"
      ],
      "queryParams": [
        "who"
      ]
    },
    "description": "Delay outage",
    "input_schema": {
      "properties": {
        "HASH": {
          "description": "Outage hash",
          "type": "string"
        },
        "delay_in_seconds": {
          "description": "Delay in seconds; a value of 0 meaning permanently delay any future alerts",
          "type": "string"
        },
        "who": {
          "description": "Indicate who has acknowledged the alert; Url format = [https://api2.panopta.com/v2/user/{user_id} or https://api2.panopta.com/v2/contact/{contact_id}]",
          "type": "string"
        }
      },
      "required": [
        "HASH",
        "delay_in_seconds",
        "who"
      ],
      "type": "object"
    },
    "name": "get_public_outage_delay",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/public/outage/{HASH}/acknowledge",
      "pathParams": [
        "HASH"
      ],
      "queryParams": [
        "who"
      ]
    },
    "description": "Acknowledge outage",
    "input_schema": {
      "properties": {
        "HASH": {
          "description": "Outage hash",
          "type": "string"
        },
        "who": {
          "description": "Indicate who has acknowledged the alert; Url format = [https://api2.panopta.com/v2/user/{user_id} or https://api2.panopta.com/v2/contact/{contact_id}]",
          "type": "string"
        }
      },
      "required": [
        "HASH",
        "who"
      ],
      "type": "object"
    },
    "name": "list_public_outage_acknowledges",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/public/outage/{HASH}/escalate",
      "pathParams": [
        "HASH"
      ],
      "queryParams": [
        "who"
      ]
    },
    "description": "Escalate outage",
    "input_schema": {
      "properties": {
        "HASH": {
          "description": "Outage hash",
          "type": "string"
        },
        "who": {
          "description": "Indicate who has acknowledged the alert; Url format = [https://api2.panopta.com/v2/user/{user_id} or https://api2.panopta.com/v2/contact/{contact_id}]",
          "type": "string"
        }
      },
      "required": [
        "HASH",
        "who"
      ],
      "type": "object"
    },
    "name": "list_public_outage_escalates",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/public/outage/{HASH}/acknowledge",
      "pathParams": [
        "HASH"
      ],
      "queryParams": []
    },
    "description": "Acknowledge outage",
    "input_schema": {
      "properties": {
        "HASH": {
          "description": "Outage hash",
          "type": "string"
        },
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "HASH",
        "body"
      ],
      "type": "object"
    },
    "name": "update_public_outage_acknowledge",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/public/outage/{HASH}/delay/{delay_in_seconds}",
      "pathParams": [
        "HASH",
        "delay_in_seconds"
      ],
      "queryParams": []
    },
    "description": "Delay outage",
    "input_schema": {
      "properties": {
        "HASH": {
          "description": "Outage hash",
          "type": "string"
        },
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "delay_in_seconds": {
          "description": "Delay in seconds; a value of 0 meaning permanently delay any future alerts",
          "type": "string"
        }
      },
      "required": [
        "HASH",
        "delay_in_seconds",
        "body"
      ],
      "type": "object"
    },
    "name": "update_public_outage_delay",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/public/outage/{HASH}/escalate",
      "pathParams": [
        "HASH"
      ],
      "queryParams": []
    },
    "description": "Escalate outage",
    "input_schema": {
      "properties": {
        "HASH": {
          "description": "Outage hash",
          "type": "string"
        },
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "HASH",
        "body"
      ],
      "type": "object"
    },
    "name": "update_public_outage_escalate",
    "tier": "readwrite"
  }
];
