// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: roles    Tools: 2
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/role/{role_id}",
      "pathParams": [
        "role_id"
      ],
      "queryParams": []
    },
    "description": "Get role",
    "input_schema": {
      "properties": {
        "role_id": {
          "description": "Role id",
          "type": "string"
        }
      },
      "required": [
        "role_id"
      ],
      "type": "object"
    },
    "name": "get_role",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/role",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get roles",
    "input_schema": {
      "type": "object"
    },
    "name": "list_roles",
    "tier": "readonly"
  }
];
