// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: rotating_contacts    Tools: 6
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/rotating_contact",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create rotating contact",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_rotating_contact",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/rotating_contact/{rotating_contact_id}",
      "pathParams": [
        "rotating_contact_id"
      ],
      "queryParams": []
    },
    "description": "Delete rotating contact",
    "input_schema": {
      "properties": {
        "rotating_contact_id": {
          "description": "Rotating contact id",
          "type": "string"
        }
      },
      "required": [
        "rotating_contact_id"
      ],
      "type": "object"
    },
    "name": "delete_rotating_contact",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/rotating_contact/{rotating_contact_id}",
      "pathParams": [
        "rotating_contact_id"
      ],
      "queryParams": []
    },
    "description": "Get rotating contact",
    "input_schema": {
      "properties": {
        "rotating_contact_id": {
          "description": "Rotating contact id",
          "type": "string"
        }
      },
      "required": [
        "rotating_contact_id"
      ],
      "type": "object"
    },
    "name": "get_rotating_contact",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/rotating_contact/{rotating_contact_id}/active",
      "pathParams": [
        "rotating_contact_id"
      ],
      "queryParams": [
        "date"
      ]
    },
    "description": "Get active contacts",
    "input_schema": {
      "properties": {
        "date": {
          "description": "Filters active contacts for a special date; format: YYYY-MM-DD",
          "type": "string"
        },
        "rotating_contact_id": {
          "description": "Rotating contact id",
          "type": "string"
        }
      },
      "required": [
        "rotating_contact_id"
      ],
      "type": "object"
    },
    "name": "list_rotating_contact_actives",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/rotating_contact",
      "pathParams": [],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get rotating contacts",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_rotating_contacts",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/rotating_contact/{rotating_contact_id}",
      "pathParams": [
        "rotating_contact_id"
      ],
      "queryParams": []
    },
    "description": "Update rotating contact",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "rotating_contact_id": {
          "description": "Rotating contact id",
          "type": "string"
        }
      },
      "required": [
        "rotating_contact_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_rotating_contact",
    "tier": "readwrite"
  }
];
