// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: server_templates    Tools: 5
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server_template",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create server template",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_server_template",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_template/{server_template_id}",
      "pathParams": [
        "server_template_id"
      ],
      "queryParams": []
    },
    "description": "Get server template",
    "input_schema": {
      "properties": {
        "server_template_id": {
          "description": "Server template id",
          "type": "string"
        }
      },
      "required": [
        "server_template_id"
      ],
      "type": "object"
    },
    "name": "get_server_template",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_template/{server_template_id}/reapply",
      "pathParams": [
        "server_template_id"
      ],
      "queryParams": []
    },
    "description": "Reapply the template",
    "input_schema": {
      "properties": {
        "server_template_id": {
          "description": "Server template id",
          "type": "string"
        }
      },
      "required": [
        "server_template_id"
      ],
      "type": "object"
    },
    "name": "list_reapplies",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_template",
      "pathParams": [],
      "queryParams": [
        "tag_filter_mode",
        "attribute_filter_mode",
        "name",
        "tags",
        "attributes",
        "server_group"
      ]
    },
    "description": "Get server templates",
    "input_schema": {
      "properties": {
        "attribute_filter_mode": {
          "default": "or",
          "description": "Mode in which to filter attributes, choices: [or, and]",
          "type": "string"
        },
        "attributes": {
          "description": "Filter results by attribute {name:value} pairs (comma separated)",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_group": {
          "description": "Filter results by server_group id",
          "type": "string"
        },
        "tag_filter_mode": {
          "default": "or",
          "description": "Mode in which to filter tags, choices: [or, and]",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_server_templates",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server_template/{server_template_id}",
      "pathParams": [
        "server_template_id"
      ],
      "queryParams": []
    },
    "description": "Update server template",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_template_id": {
          "description": "Server template id",
          "type": "string"
        }
      },
      "required": [
        "server_template_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_server_template",
    "tier": "readwrite"
  }
];
