// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: servers    Tools: 74
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/agent_resource",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Create server's agent resource",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_agent_resource",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}/countermeasure",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Create server's agent resource threshold countermeasure",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_agent_resource_threshold_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/custom_incident",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Create custom incident",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_custom_incident",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/network_service",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Create server's network service",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_network_service",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/network_service/{network_service_id}/countermeasure",
      "pathParams": [
        "server_id",
        "network_service_id"
      ],
      "queryParams": []
    },
    "description": "Create server's network service countermeasure",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_network_service_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/path_monitoring",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Create server's path monitoring",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_path_monitoring",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/request_report",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Request report",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_request_report",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/network_service/{network_service_id}/response_time/countermeasure",
      "pathParams": [
        "server_id",
        "network_service_id"
      ],
      "queryParams": []
    },
    "description": "Response time countermeasure",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_response_time_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create server",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_server",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "POST",
      "path": "/server/{server_id}/apply_monitoring_policy",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Apply monitoring policy",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "create_server_apply_monitoring_policy",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/server_attribute",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Create server's server attribute",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_server_attribute",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/server_log",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Create server's server log",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_server_log",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/snmp_resource",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Create server's snmp resource",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_snmp_resource",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server/{server_id}/template",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Create server's server template",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_template",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's agent resource",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id"
      ],
      "type": "object"
    },
    "name": "delete_agent_resource",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's agent resource threshold",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "type": "object"
    },
    "name": "delete_agent_resource_agent_resource_threshold",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}/countermeasure/{agent_resource_threshold_countermeasure_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "agent_resource_threshold_countermeasure_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's agent resource threshold countermeasure",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_countermeasure_id": {
          "description": "Agent resource threshold countermeasure id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "agent_resource_threshold_countermeasure_id"
      ],
      "type": "object"
    },
    "name": "delete_agent_resource_threshold_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/network_service/{network_service_id}",
      "pathParams": [
        "server_id",
        "network_service_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's network service",
    "input_schema": {
      "properties": {
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id"
      ],
      "type": "object"
    },
    "name": "delete_network_service",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/network_service/{network_service_id}/countermeasure/{network_service_countermeasure_id}",
      "pathParams": [
        "server_id",
        "network_service_id",
        "network_service_countermeasure_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's network service countermeasure",
    "input_schema": {
      "properties": {
        "network_service_countermeasure_id": {
          "description": "Network service countermeasure id",
          "type": "string"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "network_service_countermeasure_id"
      ],
      "type": "object"
    },
    "name": "delete_network_service_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/path_monitoring/{path_monitoring_id}",
      "pathParams": [
        "server_id",
        "path_monitoring_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's path monitoring",
    "input_schema": {
      "properties": {
        "path_monitoring_id": {
          "description": "Path monitoring id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "path_monitoring_id"
      ],
      "type": "object"
    },
    "name": "delete_path_monitoring",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/network_service/{network_service_id}/response_time/countermeasure/{network_service_response_time_countermeasure_id}",
      "pathParams": [
        "server_id",
        "network_service_id",
        "network_service_response_time_countermeasure_id"
      ],
      "queryParams": []
    },
    "description": "Edit response time countermeasure",
    "input_schema": {
      "properties": {
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "network_service_response_time_countermeasure_id": {
          "description": "Network service response time countermeasure id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "network_service_response_time_countermeasure_id"
      ],
      "type": "object"
    },
    "name": "delete_response_time_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Delete server",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "delete_server",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/server_attribute/{server_attribute_id}",
      "pathParams": [
        "server_id",
        "server_attribute_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's server attribute",
    "input_schema": {
      "properties": {
        "server_attribute_id": {
          "description": "Server attribute id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "server_attribute_id"
      ],
      "type": "object"
    },
    "name": "delete_server_attribute",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/snmp_resource/{snmp_resource_id}",
      "pathParams": [
        "server_id",
        "snmp_resource_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's snmp resource",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "snmp_resource_id": {
          "description": "Snmp resource id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "snmp_resource_id"
      ],
      "type": "object"
    },
    "name": "delete_snmp_resource",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/snmp_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's agent resource threshold",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "type": "object"
    },
    "name": "delete_snmp_resource_agent_resource_threshold",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server/{server_id}/template/{server_template_id}",
      "pathParams": [
        "server_id",
        "server_template_id"
      ],
      "queryParams": []
    },
    "description": "Delete server's server template",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "server_template_id": {
          "description": "Server template id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "server_template_id"
      ],
      "type": "object"
    },
    "name": "delete_template",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id"
      ],
      "queryParams": []
    },
    "description": "Get server's agent resource",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id"
      ],
      "type": "object"
    },
    "name": "get_agent_resource",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Get server's agent resource threshold",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "type": "object"
    },
    "name": "get_agent_resource_agent_resource_threshold",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/metric/{timescale}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "timescale"
      ],
      "queryParams": [
        "end_time",
        "aggregate"
      ]
    },
    "description": "Get agent resource metric graph data",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "aggregate": {
          "description": "Whether to aggregate metric values into time slices",
          "type": "string"
        },
        "end_time": {
          "description": "End time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "timescale": {
          "description": "('hour', 'day', 'week', 'month', or 'year')",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "timescale"
      ],
      "type": "object"
    },
    "name": "get_agent_resource_metric",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}/countermeasure/{agent_resource_threshold_countermeasure_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "agent_resource_threshold_countermeasure_id"
      ],
      "queryParams": []
    },
    "description": "Get server's agent resource threshold countermeasure",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_countermeasure_id": {
          "description": "Agent resource threshold countermeasure id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "agent_resource_threshold_countermeasure_id"
      ],
      "type": "object"
    },
    "name": "get_agent_resource_threshold_countermeasure",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/fabric_resource/{fabric_resource_id}/metric/{timescale}",
      "pathParams": [
        "server_id",
        "fabric_resource_id",
        "timescale"
      ],
      "queryParams": [
        "end_time",
        "aggregate"
      ]
    },
    "description": "Get fabric resource metric graph data",
    "input_schema": {
      "properties": {
        "aggregate": {
          "description": "Whether to aggregate metric values into time slices",
          "type": "string"
        },
        "end_time": {
          "description": "End time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "fabric_resource_id": {
          "description": "Fabric resource id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "timescale": {
          "description": "('hour', 'day', 'week', 'month', or 'year')",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "fabric_resource_id",
        "timescale"
      ],
      "type": "object"
    },
    "name": "get_fabric_resource_metric",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/network_service/{network_service_id}/countermeasure/{network_service_countermeasure_id}",
      "pathParams": [
        "server_id",
        "network_service_id",
        "network_service_countermeasure_id"
      ],
      "queryParams": []
    },
    "description": "Get server's network service countermeasure",
    "input_schema": {
      "properties": {
        "network_service_countermeasure_id": {
          "description": "Network service countermeasure id",
          "type": "string"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "network_service_countermeasure_id"
      ],
      "type": "object"
    },
    "name": "get_network_service_countermeasure",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/path_monitoring/{path_monitoring_id}",
      "pathParams": [
        "server_id",
        "path_monitoring_id"
      ],
      "queryParams": []
    },
    "description": "Get server's path monitoring",
    "input_schema": {
      "properties": {
        "path_monitoring_id": {
          "description": "Path monitoring id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "path_monitoring_id"
      ],
      "type": "object"
    },
    "name": "get_path_monitoring",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/network_service/{network_service_id}/response_time/countermeasure/{network_service_response_time_countermeasure_id}",
      "pathParams": [
        "server_id",
        "network_service_id",
        "network_service_response_time_countermeasure_id"
      ],
      "queryParams": [
        "delay",
        "rank",
        "needs_approval",
        "slack_output",
        "countermeasure_metadata"
      ]
    },
    "description": "Edit response time countermeasure",
    "input_schema": {
      "properties": {
        "countermeasure_metadata": {
          "description": " Url format = https://api2.panopta.com/v2/countermeasure_metadata/{countermeasure_metadata_id}",
          "type": "string"
        },
        "delay": {
          "type": "string"
        },
        "needs_approval": {
          "type": "string"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "network_service_response_time_countermeasure_id": {
          "description": "Network service response time countermeasure id",
          "type": "string"
        },
        "rank": {
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "slack_output": {
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "network_service_response_time_countermeasure_id"
      ],
      "type": "object"
    },
    "name": "get_response_time_countermeasure",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Get server",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "get_server",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/server_attribute/{server_attribute_id}",
      "pathParams": [
        "server_id",
        "server_attribute_id"
      ],
      "queryParams": []
    },
    "description": "Get server's server attribute",
    "input_schema": {
      "properties": {
        "server_attribute_id": {
          "description": "Server attribute id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "server_attribute_id"
      ],
      "type": "object"
    },
    "name": "get_server_attribute",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/countermeasure_metadata/{countermeasure_metadata_id}",
      "pathParams": [
        "server_id",
        "countermeasure_metadata_id"
      ],
      "queryParams": []
    },
    "description": "Get server's countermeasure metadata",
    "input_schema": {
      "properties": {
        "countermeasure_metadata_id": {
          "description": "Countermeasure metadata id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "countermeasure_metadata_id"
      ],
      "type": "object"
    },
    "name": "get_server_countermeasure_metadata",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/network_service/{network_service_id}",
      "pathParams": [
        "server_id",
        "network_service_id"
      ],
      "queryParams": []
    },
    "description": "Get server's network service",
    "input_schema": {
      "properties": {
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id"
      ],
      "type": "object"
    },
    "name": "get_server_network_service",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/network_service/{network_service_id}/response_time/{timescale}",
      "pathParams": [
        "server_id",
        "network_service_id",
        "timescale"
      ],
      "queryParams": [
        "end_time",
        "aggregate"
      ]
    },
    "description": "Get service response time graph data",
    "input_schema": {
      "properties": {
        "aggregate": {
          "description": "Whether to aggregate metric values into time slices",
          "type": "string"
        },
        "end_time": {
          "description": "End time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "timescale": {
          "description": "('hour', 'day', 'week', 'month', or 'year')",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "timescale"
      ],
      "type": "object"
    },
    "name": "get_server_network_service_response_time",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/snmp_resource/{snmp_resource_id}",
      "pathParams": [
        "server_id",
        "snmp_resource_id"
      ],
      "queryParams": []
    },
    "description": "Get server's snmp resource",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "snmp_resource_id": {
          "description": "Snmp resource id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "snmp_resource_id"
      ],
      "type": "object"
    },
    "name": "get_snmp_resource",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/snmp_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Get server's agent resource threshold",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "type": "object"
    },
    "name": "get_snmp_resource_agent_resource_threshold",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/snmp_resource/{snmp_resource_id}/metric/{timescale}",
      "pathParams": [
        "server_id",
        "snmp_resource_id",
        "timescale"
      ],
      "queryParams": [
        "end_time",
        "aggregate"
      ]
    },
    "description": "Get snmp resource metric graph data",
    "input_schema": {
      "properties": {
        "aggregate": {
          "description": "Whether to aggregate metric values into time slices",
          "type": "string"
        },
        "end_time": {
          "description": "End time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "snmp_resource_id": {
          "description": "Snmp resource id",
          "type": "string"
        },
        "timescale": {
          "description": "('hour', 'day', 'week', 'month', or 'year')",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "snmp_resource_id",
        "timescale"
      ],
      "type": "object"
    },
    "name": "get_snmp_resource_metric",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}/countermeasure",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Get server's agent resource threshold countermeasures",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "type": "object"
    },
    "name": "list_agent_resource_threshold_countermeasures",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/agent_resource",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "name",
        "tags",
        "monitoring_location"
      ]
    },
    "description": "Get server's agent resources",
    "input_schema": {
      "properties": {
        "monitoring_location": {
          "description": "Filter results by monitoring location URL either server (https://api2.panopta.com/v2/server/{server_id}), appliance (https://api2.panopta.com/v2/onsight/{onsight_id}), or monitor node (https://api2.panopta.com/v2/monitoring_node/{monitoring_node_id})",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_agent_resources",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/child_compound_service",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "name",
        "tags"
      ]
    },
    "description": "Get server's compound services",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_child_compound_services",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/child_server",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "name",
        "fqdn",
        "server_key",
        "partner_server_id",
        "tags",
        "attributes",
        "server_group",
        "status"
      ]
    },
    "description": "Get server's servers",
    "input_schema": {
      "properties": {
        "attributes": {
          "description": "Filter results by attribute {name:value} pairs (comma separated)",
          "type": "string"
        },
        "fqdn": {
          "description": "Filter results by fqdn",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "partner_server_id": {
          "description": "Filter results by partner_server_id",
          "type": "string"
        },
        "server_group": {
          "description": "Filter results by server_group id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "server_key": {
          "description": "Filter results by server_key",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "suspended",
            "deleted",
            "pending"
          ],
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_child_servers",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/network_service/{network_service_id}/countermeasure",
      "pathParams": [
        "server_id",
        "network_service_id"
      ],
      "queryParams": []
    },
    "description": "Get server's network service countermeasures",
    "input_schema": {
      "properties": {
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id"
      ],
      "type": "object"
    },
    "name": "list_network_service_countermeasures",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/path_monitoring",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "location"
      ]
    },
    "description": "Get server's path monitorings",
    "input_schema": {
      "properties": {
        "location": {
          "description": "Filter results by monitoring location URL either server (https://api2.panopta.com/v2/server/{server_id}), appliance (https://api2.panopta.com/v2/onsight/{onsight_id}), or monitor node (https://api2.panopta.com/v2/monitoring_node/{monitoring_node_id})",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_path_monitorings",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/network_service/{network_service_id}/response_time/countermeasure",
      "pathParams": [
        "server_id",
        "network_service_id"
      ],
      "queryParams": [
        "delay",
        "rank",
        "needs_approval",
        "slack_output",
        "countermeasure_metadata"
      ]
    },
    "description": "Response time countermeasure",
    "input_schema": {
      "properties": {
        "countermeasure_metadata": {
          "description": " Url format = https://api2.panopta.com/v2/countermeasure_metadata/{countermeasure_metadata_id}",
          "type": "string"
        },
        "delay": {
          "type": "string"
        },
        "needs_approval": {
          "type": "string"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "rank": {
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "slack_output": {
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id"
      ],
      "type": "object"
    },
    "name": "list_response_time_countermeasures",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/path_monitoring/{path_monitoring_id}/results",
      "pathParams": [
        "server_id",
        "path_monitoring_id"
      ],
      "queryParams": [
        "start_time",
        "end_time"
      ]
    },
    "description": "Get path monitoring results",
    "input_schema": {
      "properties": {
        "end_time": {
          "description": "Start time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "path_monitoring_id": {
          "description": "Path monitoring id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "start_time": {
          "description": "Start time in UTC; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "path_monitoring_id"
      ],
      "type": "object"
    },
    "name": "list_resultses",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/server_attribute",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Get server's server attributes",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_server_attributes",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/availability",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "start_time",
        "end_time",
        "with_excluded_outages"
      ]
    },
    "description": "Get server availability",
    "input_schema": {
      "properties": {
        "end_time": {
          "description": "End time of the range; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "start_time": {
          "description": "Start time of the range; format: YYYY-MM-DD HH:MM:SS",
          "type": "string"
        },
        "with_excluded_outages": {
          "description": "Include the outages that had been marked as excluded",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "start_time",
        "end_time"
      ],
      "type": "object"
    },
    "name": "list_server_availabilities",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/countermeasure_metadata",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "status"
      ]
    },
    "description": "Get server's countermeasure metadatas",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "pending",
            "available",
            "unavailable"
          ],
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_server_countermeasure_metadatas",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/server_log",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Get server's server logs",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_server_logs",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/maintenance_schedule",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get server's maintenance schedules",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_server_maintenance_schedules",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/network_service",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "ip_type",
        "name",
        "service_type",
        "server_interface",
        "status",
        "tags",
        "monitoring_location"
      ]
    },
    "description": "Get server's network services",
    "input_schema": {
      "properties": {
        "ip_type": {
          "description": "Mode in which to filter by ip type, choices: [v4, v6]",
          "type": "string"
        },
        "monitoring_location": {
          "description": "Filter results by monitoring location URL either server (https://api2.panopta.com/v2/server/{server_id}), appliance (https://api2.panopta.com/v2/onsight/{onsight_id}), or monitor node (https://api2.panopta.com/v2/monitoring_node/{monitoring_node_id})",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "server_interface": {
          "description": "Filter results by server_interface",
          "type": "string"
        },
        "service_type": {
          "description": "Filter results by service_type id",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "suspended"
          ],
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_server_network_services",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/outage",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "server",
        "severity",
        "status",
        "end_time",
        "start_time"
      ]
    },
    "description": "Get server's outages",
    "input_schema": {
      "properties": {
        "end_time": {
          "description": "End_time in UTC",
          "type": "string"
        },
        "server": {
          "description": "Filter results by server id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "severity": {
          "description": "Filter results by severity",
          "enum": [
            "critical",
            "warning"
          ],
          "type": "string"
        },
        "start_time": {
          "description": "Start_time in UTC",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "resolved"
          ],
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_server_outages",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/server_resource_metadata",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Get server resource metadata",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_server_resource_metadatas",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server",
      "pathParams": [],
      "queryParams": [
        "tag_filter_mode",
        "attribute_filter_mode",
        "name",
        "fqdn",
        "server_key",
        "partner_server_id",
        "tags",
        "attributes",
        "server_group",
        "status"
      ]
    },
    "description": "Get servers",
    "input_schema": {
      "properties": {
        "attribute_filter_mode": {
          "default": "or",
          "description": "Mode in which to filter attributes, choices: [or, and]",
          "type": "string"
        },
        "attributes": {
          "description": "Filter results by attribute {name:value} pairs (comma separated)",
          "type": "string"
        },
        "fqdn": {
          "description": "Filter results by fqdn",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "partner_server_id": {
          "description": "Filter results by partner_server_id",
          "type": "string"
        },
        "server_group": {
          "description": "Filter results by server_group id",
          "type": "string"
        },
        "server_key": {
          "description": "Filter results by server_key",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "suspended",
            "deleted",
            "pending"
          ],
          "type": "string"
        },
        "tag_filter_mode": {
          "default": "or",
          "description": "Mode in which to filter tags, choices: [or, and]",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_servers",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/snmp_resource",
      "pathParams": [
        "server_id"
      ],
      "queryParams": [
        "name",
        "base_oid",
        "tags"
      ]
    },
    "description": "Get server's snmp resources",
    "input_schema": {
      "properties": {
        "base_oid": {
          "description": "Filter results by base_oid",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_snmp_resources",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server/{server_id}/template",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Get server's server templates",
    "input_schema": {
      "properties": {
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id"
      ],
      "type": "object"
    },
    "name": "list_templates",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id"
      ],
      "queryParams": []
    },
    "description": "Update server's agent resource",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_agent_resource",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Update server's agent resource threshold",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_agent_resource_agent_resource_threshold",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/agent_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}/countermeasure/{agent_resource_threshold_countermeasure_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "agent_resource_threshold_countermeasure_id"
      ],
      "queryParams": []
    },
    "description": "Update server's agent resource threshold countermeasure",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_countermeasure_id": {
          "description": "Agent resource threshold countermeasure id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "agent_resource_threshold_countermeasure_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_agent_resource_threshold_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/change_customer",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Move server between customers",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_change_customer",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/flush_dns",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Flush server DNS cache",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_flush_dns",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/network_service/{network_service_id}",
      "pathParams": [
        "server_id",
        "network_service_id"
      ],
      "queryParams": []
    },
    "description": "Update server's network service",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_network_service",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/network_service/{network_service_id}/countermeasure/{network_service_countermeasure_id}",
      "pathParams": [
        "server_id",
        "network_service_id",
        "network_service_countermeasure_id"
      ],
      "queryParams": []
    },
    "description": "Update server's network service countermeasure",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "network_service_countermeasure_id": {
          "description": "Network service countermeasure id",
          "type": "string"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "network_service_countermeasure_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_network_service_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/network_service/{network_service_id}/response_time/countermeasure/{network_service_response_time_countermeasure_id}",
      "pathParams": [
        "server_id",
        "network_service_id",
        "network_service_response_time_countermeasure_id"
      ],
      "queryParams": []
    },
    "description": "Edit response time countermeasure",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "network_service_id": {
          "description": "Network service id",
          "type": "string"
        },
        "network_service_response_time_countermeasure_id": {
          "description": "Network service response time countermeasure id",
          "type": "string"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "network_service_id",
        "network_service_response_time_countermeasure_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_response_time_countermeasure",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Update server",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_server",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/simulate_outage",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Simulate outage",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_simulate_outage",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/snmp_discovery",
      "pathParams": [
        "server_id"
      ],
      "queryParams": []
    },
    "description": "Request SNMP discovery",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_snmp_discovery",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/snmp_resource/{snmp_resource_id}",
      "pathParams": [
        "server_id",
        "snmp_resource_id"
      ],
      "queryParams": []
    },
    "description": "Update server's snmp resource",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        },
        "snmp_resource_id": {
          "description": "Snmp resource id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "snmp_resource_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_snmp_resource",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server/{server_id}/snmp_resource/{agent_resource_id}/agent_resource_threshold/{agent_resource_threshold_id}",
      "pathParams": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id"
      ],
      "queryParams": []
    },
    "description": "Update server's agent resource threshold",
    "input_schema": {
      "properties": {
        "agent_resource_id": {
          "description": "Agent resource id",
          "type": "string"
        },
        "agent_resource_threshold_id": {
          "description": "Agent resource threshold id",
          "type": "string"
        },
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_id": {
          "description": "Server id",
          "type": "string"
        }
      },
      "required": [
        "server_id",
        "agent_resource_id",
        "agent_resource_threshold_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_snmp_resource_agent_resource_threshold",
    "tier": "readwrite"
  }
];
