// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: server_attribute_types    Tools: 5
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server_attribute_type",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create server attribute type",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_server_attribute_type",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server_attribute_type/{server_attribute_type_id}",
      "pathParams": [
        "server_attribute_type_id"
      ],
      "queryParams": []
    },
    "description": "Delete server attribute type",
    "input_schema": {
      "properties": {
        "server_attribute_type_id": {
          "description": "Server attribute type id",
          "type": "string"
        }
      },
      "required": [
        "server_attribute_type_id"
      ],
      "type": "object"
    },
    "name": "delete_server_attribute_type",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_attribute_type/{server_attribute_type_id}",
      "pathParams": [
        "server_attribute_type_id"
      ],
      "queryParams": []
    },
    "description": "Get server attribute type",
    "input_schema": {
      "properties": {
        "server_attribute_type_id": {
          "description": "Server attribute type id",
          "type": "string"
        }
      },
      "required": [
        "server_attribute_type_id"
      ],
      "type": "object"
    },
    "name": "get_server_attribute_type",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_attribute_type",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get server attribute types",
    "input_schema": {
      "type": "object"
    },
    "name": "list_server_attribute_types",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server_attribute_type/{server_attribute_type_id}",
      "pathParams": [
        "server_attribute_type_id"
      ],
      "queryParams": []
    },
    "description": "Update server attribute type",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_attribute_type_id": {
          "description": "Server attribute type id",
          "type": "string"
        }
      },
      "required": [
        "server_attribute_type_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_server_attribute_type",
    "tier": "readwrite"
  }
];
