// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: server_groups    Tools: 13
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server_group",
      "pathParams": [],
      "queryParams": [
        "root_only"
      ]
    },
    "description": "Create server group",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "root_only": {
          "type": "string"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_server_group",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "POST",
      "path": "/server_group/{server_group_id}/apply_monitoring_policy",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": []
    },
    "description": "Apply monitoring policy",
    "input_schema": {
      "properties": {
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        }
      },
      "required": [
        "server_group_id"
      ],
      "type": "object"
    },
    "name": "create_server_group_apply_monitoring_policy",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/server_group/{server_group_id}/templates",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": []
    },
    "description": "Create server group's templates",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        }
      },
      "required": [
        "server_group_id",
        "body"
      ],
      "type": "object"
    },
    "name": "create_templates",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server_group/{server_group_id}",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": [
        "root_only"
      ]
    },
    "description": "Delete server group",
    "input_schema": {
      "properties": {
        "root_only": {
          "type": "string"
        },
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        }
      },
      "required": [
        "server_group_id"
      ],
      "type": "object"
    },
    "name": "delete_server_group",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/server_group/{server_group_id}/templates/{templates_id}",
      "pathParams": [
        "server_group_id",
        "templates_id"
      ],
      "queryParams": []
    },
    "description": "Delete server group's templates",
    "input_schema": {
      "properties": {
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        },
        "templates_id": {
          "description": "Templates id",
          "type": "string"
        }
      },
      "required": [
        "server_group_id",
        "templates_id"
      ],
      "type": "object"
    },
    "name": "delete_templates",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_group/{server_group_id}",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": [
        "root_only"
      ]
    },
    "description": "Get server group",
    "input_schema": {
      "properties": {
        "root_only": {
          "type": "string"
        },
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        }
      },
      "required": [
        "server_group_id"
      ],
      "type": "object"
    },
    "name": "get_server_group",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_group/{server_group_id}/compound_service",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": [
        "name",
        "tags"
      ]
    },
    "description": "Get server group's compound services",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "server_group_id"
      ],
      "type": "object"
    },
    "name": "list_server_group_compound_services",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_group/{server_group_id}/onsight",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": [
        "name"
      ]
    },
    "description": "Get server group's onsights",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        }
      },
      "required": [
        "server_group_id"
      ],
      "type": "object"
    },
    "name": "list_server_group_onsights",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_group/{server_group_id}/server_group",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": [
        "name",
        "tags",
        "root_only"
      ]
    },
    "description": "Get server group's server groups",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "root_only": {
          "type": "string"
        },
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "server_group_id"
      ],
      "type": "object"
    },
    "name": "list_server_group_server_groups",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_group/{server_group_id}/server",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": [
        "name",
        "fqdn",
        "server_key",
        "partner_server_id",
        "tags",
        "attributes",
        "server_group",
        "status"
      ]
    },
    "description": "Get server group's servers",
    "input_schema": {
      "properties": {
        "attributes": {
          "description": "Filter results by attribute {name:value} pairs (comma separated)",
          "type": "string"
        },
        "fqdn": {
          "description": "Filter results by fqdn",
          "type": "string"
        },
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "partner_server_id": {
          "description": "Filter results by partner_server_id",
          "type": "string"
        },
        "server_group": {
          "description": "Filter results by server_group id",
          "type": "string"
        },
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        },
        "server_key": {
          "description": "Filter results by server_key",
          "type": "string"
        },
        "status": {
          "description": "Filter results by status",
          "enum": [
            "active",
            "suspended",
            "deleted",
            "pending"
          ],
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "required": [
        "server_group_id"
      ],
      "type": "object"
    },
    "name": "list_server_group_servers",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_group",
      "pathParams": [],
      "queryParams": [
        "name",
        "tags",
        "root_only"
      ]
    },
    "description": "Get server groups",
    "input_schema": {
      "properties": {
        "name": {
          "description": "Filter results by name",
          "type": "string"
        },
        "root_only": {
          "type": "string"
        },
        "tags": {
          "description": "Filter results by tags (comma separated)",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_server_groups",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/server_group/{server_group_id}/templates",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": []
    },
    "description": "Get server group's templatess",
    "input_schema": {
      "properties": {
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        }
      },
      "required": [
        "server_group_id"
      ],
      "type": "object"
    },
    "name": "list_templateses",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/server_group/{server_group_id}",
      "pathParams": [
        "server_group_id"
      ],
      "queryParams": [
        "root_only"
      ]
    },
    "description": "Update server group",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "root_only": {
          "type": "string"
        },
        "server_group_id": {
          "description": "Server group id",
          "type": "string"
        }
      },
      "required": [
        "server_group_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_server_group",
    "tier": "readwrite"
  }
];
