// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: snmp_credentials    Tools: 5
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/snmp_credential",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create snmp credential",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_snmp_credential",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/snmp_credential/{snmp_credential_id}",
      "pathParams": [
        "snmp_credential_id"
      ],
      "queryParams": []
    },
    "description": "Delete snmp credential",
    "input_schema": {
      "properties": {
        "snmp_credential_id": {
          "description": "Snmp credential id",
          "type": "string"
        }
      },
      "required": [
        "snmp_credential_id"
      ],
      "type": "object"
    },
    "name": "delete_snmp_credential",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/snmp_credential/{snmp_credential_id}",
      "pathParams": [
        "snmp_credential_id"
      ],
      "queryParams": []
    },
    "description": "Get snmp credential",
    "input_schema": {
      "properties": {
        "snmp_credential_id": {
          "description": "Snmp credential id",
          "type": "string"
        }
      },
      "required": [
        "snmp_credential_id"
      ],
      "type": "object"
    },
    "name": "get_snmp_credential",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/snmp_credential",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get snmp credentials",
    "input_schema": {
      "type": "object"
    },
    "name": "list_snmp_credentials",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/snmp_credential/{snmp_credential_id}",
      "pathParams": [
        "snmp_credential_id"
      ],
      "queryParams": []
    },
    "description": "Update snmp credential",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "snmp_credential_id": {
          "description": "Snmp credential id",
          "type": "string"
        }
      },
      "required": [
        "snmp_credential_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_snmp_credential",
    "tier": "readwrite"
  }
];
