// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: status_pages    Tools: 3
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/status_page",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create status page",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_status_page",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/status_page/{status_page_id}",
      "pathParams": [
        "status_page_id"
      ],
      "queryParams": []
    },
    "description": "Delete status page",
    "input_schema": {
      "properties": {
        "status_page_id": {
          "description": "Status page id",
          "type": "string"
        }
      },
      "required": [
        "status_page_id"
      ],
      "type": "object"
    },
    "name": "delete_status_page",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/status_page/{status_page_id}",
      "pathParams": [
        "status_page_id"
      ],
      "queryParams": []
    },
    "description": "Update status page",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "status_page_id": {
          "description": "Status page id",
          "type": "string"
        }
      },
      "required": [
        "status_page_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_status_page",
    "tier": "readwrite"
  }
];
