// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: timezones    Tools: 2
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/timezone/{timezone_id}",
      "pathParams": [
        "timezone_id"
      ],
      "queryParams": []
    },
    "description": "Get timezone",
    "input_schema": {
      "properties": {
        "timezone_id": {
          "description": "Timezone id",
          "type": "string"
        }
      },
      "required": [
        "timezone_id"
      ],
      "type": "object"
    },
    "name": "get_timezone",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/timezone",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Get timezones",
    "input_schema": {
      "type": "object"
    },
    "name": "list_timezones",
    "tier": "readonly"
  }
];
