// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.
// Source: schema-discovery OpenAPI compiled spec.
// Run: npm run codegen:ask-claude-tools
//
// Domain: users    Tools: 6
export const TOOLS = [
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "POST",
      "path": "/user",
      "pathParams": [],
      "queryParams": []
    },
    "description": "Create user",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "name": "create_user",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "DELETE",
      "path": "/user/{user_id}",
      "pathParams": [
        "user_id"
      ],
      "queryParams": []
    },
    "description": "Delete user",
    "input_schema": {
      "properties": {
        "user_id": {
          "description": "User id",
          "type": "string"
        }
      },
      "required": [
        "user_id"
      ],
      "type": "object"
    },
    "name": "delete_user",
    "tier": "readwrite"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/user/{user_id}",
      "pathParams": [
        "user_id"
      ],
      "queryParams": []
    },
    "description": "Get user",
    "input_schema": {
      "properties": {
        "user_id": {
          "description": "User id",
          "type": "string"
        }
      },
      "required": [
        "user_id"
      ],
      "type": "object"
    },
    "name": "get_user",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/user/getaddons",
      "pathParams": [],
      "queryParams": [
        "user_id"
      ]
    },
    "description": "Get addons",
    "input_schema": {
      "properties": {
        "user_id": {
          "description": "Id of the user",
          "type": "string"
        }
      },
      "required": [
        "user_id"
      ],
      "type": "object"
    },
    "name": "list_getaddonses",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [],
      "method": "GET",
      "path": "/user",
      "pathParams": [],
      "queryParams": [
        "username"
      ]
    },
    "description": "Get users",
    "input_schema": {
      "properties": {
        "username": {
          "description": "Filter results by username",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_users",
    "tier": "readonly"
  },
  {
    "_spec": {
      "bodyParams": [
        "body"
      ],
      "method": "PUT",
      "path": "/user/{user_id}",
      "pathParams": [
        "user_id"
      ],
      "queryParams": []
    },
    "description": "Update user",
    "input_schema": {
      "properties": {
        "body": {
          "description": "Request body (see API docs).",
          "type": "object"
        },
        "user_id": {
          "description": "User id",
          "type": "string"
        }
      },
      "required": [
        "user_id",
        "body"
      ],
      "type": "object"
    },
    "name": "update_user",
    "tier": "readwrite"
  }
];
