// Unofficial FortiMonitor Toolkit — Gregori Jenkins <https://www.linkedin.com/in/gregorijenkins>
// Step-2 review audit CSV (FMN-60 / FMN-64).
//
// Produces a two-section report:
//   Section 1 — Group Summary (1 row per group, sorted by descending device_count)
//   Section 2 — Per-Group Detail (per group: port table + full device table)
//
// Used by the Remove and Add review steps via the "Download audit (CSV)"
// button. All data is preserved — no truncation of device lists or port
// fields; the operator can load this into Excel, split by section, and
// reshape freely.

const GENERATOR = Object.freeze({
  tool: 'Unofficial FortiMonitor Toolkit',
  author: 'Gregori Jenkins',
  url: 'https://www.linkedin.com/in/gregorijenkins'
});

/**
 * @param {object} args
 * @param {Array<{ fingerprint:string, devices:Array, portsData:{ports:Array} }>} args.groups
 * @param {Map<string, { skipped:boolean, removePortNames?:string[], addPortNames?:string[] }>} args.decisions
 * @param {Record<string,string>} args.nameById
 * @param {'remove'|'add'} args.toolMode
 * @param {string} [args.batchId]
 * @returns {string} CSV text including attribution header
 */
export function buildAuditCsv({ groups, decisions, nameById = {}, toolMode, batchId }) {
  const verb = toolMode === 'add' ? 'add' : 'remove';
  const totalGroups = groups.length;

  // Preserve original 1-based group_number after the descending-device-count sort.
  const indexed = groups.map((group, i) => ({ group, originalIndex: i + 1 }));
  indexed.sort((a, b) => {
    const diff = b.group.devices.length - a.group.devices.length;
    return diff !== 0 ? diff : a.originalIndex - b.originalIndex;
  });

  const now = new Date().toISOString();
  const lines = [];

  lines.push(`# Generated by ${GENERATOR.tool} (${verb} — review audit) on ${now}`);
  lines.push(`# Author: ${GENERATOR.author} — ${GENERATOR.url}`);
  if (batchId) lines.push(`# Batch: ${batchId}`);
  lines.push(`# ${totalGroups} group${totalGroups === 1 ? '' : 's'}, sorted by descending device_count`);
  lines.push('#');

  // --- Section 1: Group Summary ---
  lines.push('# Section 1: Group Summary');
  lines.push('');
  lines.push(csvRow(['group_number', 'group_fingerprint', 'device_count', 'port_count_per_device', 'proposed_action', 'ports_marked']));
  for (const { group, originalIndex } of indexed) {
    const decision = decisions?.get(group.fingerprint);
    const ports = group.portsData?.ports ?? [];
    const deviceCount = group.devices.length;
    const markedPorts = decisionMarkedPorts(decision, toolMode);
    const action = decisionActionSummary(decision, markedPorts, verb);
    lines.push(csvRow([
      String(originalIndex),
      group.fingerprint ?? '',
      String(deviceCount),
      String(ports.length),
      action,
      markedPorts.join('|')
    ]));
  }

  lines.push('');
  lines.push('# Section 2: Per-Group Detail');
  lines.push('');

  // --- Section 2: Per-Group Detail ---
  for (const { group, originalIndex } of indexed) {
    const decision = decisions?.get(group.fingerprint);
    const ports = group.portsData?.ports ?? [];
    const deviceCount = group.devices.length;
    const markedPorts = decisionMarkedPorts(decision, toolMode);
    const action = decisionActionSummary(decision, markedPorts, verb);
    const selected = new Set(markedPorts);

    lines.push(`# Group ${originalIndex} of ${totalGroups} — fingerprint=${group.fingerprint ?? ''} — ${deviceCount} device${deviceCount === 1 ? '' : 's'} — action: ${action}`);
    lines.push('');

    // Ports table
    lines.push(`# Ports (${ports.length})`);
    lines.push(csvRow(['port_name', 'admin_status', 'oper_status', 'is_active', 'proposed_action']));
    for (const port of ports) {
      let portAction;
      if (!decision) portAction = 'undecided';
      else if (decision.skipped) portAction = 'skipped';
      else if (selected.has(port.name)) portAction = verb;
      else portAction = 'keep';
      lines.push(csvRow([
        port.name ?? '',
        port.admin_status ?? '',
        port.oper_status ?? '',
        port.isActive ? 'yes' : 'no',
        portAction
      ]));
    }

    lines.push('');

    // Devices table — full list, no truncation.
    lines.push(`# Devices (${deviceCount})`);
    lines.push(csvRow(['server_id', 'device_name']));
    for (const device of group.devices) {
      const name = nameById[String(device.serverId)] ?? String(device.serverId);
      lines.push(csvRow([String(device.serverId), name]));
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function auditCsvFilename(batchId, toolMode) {
  const stem = batchId || 'audit';
  const suffix = toolMode === 'add' ? '-add' : '';
  return `${stem}${suffix}-review.csv`;
}

function decisionMarkedPorts(decision, toolMode) {
  if (!decision || decision.skipped) return [];
  return toolMode === 'add'
    ? (decision.addPortNames ?? [])
    : (decision.removePortNames ?? []);
}

function decisionActionSummary(decision, markedPorts, verb) {
  if (!decision) return 'undecided';
  if (decision.skipped) return 'skipped';
  if (markedPorts.length === 0) return 'undecided';
  return `${verb}: ${markedPorts.join(', ')}`;
}

function csvRow(cells) {
  return cells.map(csvEscape).join(',');
}

function csvEscape(v) {
  const s = String(v ?? '');
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}
