// Unofficial FortiMonitor Toolkit — Gregori Jenkins <https://www.linkedin.com/in/gregorijenkins>
// Step-2 review audit CSV. Produces a per-port snapshot of every group
// in the current scan, reflecting whatever decisions the operator has
// made so far. Used by the Remove and Add review steps via the
// Download audit button.

const GENERATOR = Object.freeze({
  tool: 'Unofficial FortiMonitor Toolkit',
  author: 'Gregori Jenkins',
  url: 'https://www.linkedin.com/in/gregorijenkins'
});

/**
 * @param {object} args
 * @param {Array<{ fingerprint:string, devices:Array, portsData:{ports:Array} }>} args.groups
 * @param {Map<string, { skipped:boolean, removePortNames?:string[], addPortNames?:string[] }>} args.decisions
 * @param {Record<string,string>} args.nameById
 * @param {'remove'|'add'} args.toolMode
 * @param {string} [args.batchId]
 * @returns {string} CSV text including attribution header
 */
export function buildAuditCsv({ groups, decisions, nameById = {}, toolMode, batchId }) {
  const rows = [[
    'group_number',
    'group_fingerprint',
    'port_name',
    'admin_status',
    'oper_status',
    'proposed_action',
    'device_count',
    'sample_device_names'
  ]];

  const verb = toolMode === 'add' ? 'add' : 'remove';

  groups.forEach((g, i) => {
    const groupNumber = i + 1;
    const decision = decisions?.get(g.fingerprint);
    const deviceCount = g.devices.length;
    const sampleList = g.devices.slice(0, 20)
      .map((d) => nameById[String(d.serverId)] ?? String(d.serverId));
    const sampleNames = sampleList.join('|')
      + (g.devices.length > 20 ? `|+${g.devices.length - 20} more` : '');

    const selected = toolMode === 'add'
      ? new Set(decision?.addPortNames ?? [])
      : new Set(decision?.removePortNames ?? []);

    const ports = g.portsData?.ports ?? [];
    for (const port of ports) {
      let action;
      if (!decision) action = 'undecided';
      else if (decision.skipped) action = 'skipped';
      else if (selected.has(port.name)) action = verb;
      else action = 'keep';

      rows.push([
        String(groupNumber),
        String(g.fingerprint ?? ''),
        String(port.name ?? ''),
        String(port.admin_status ?? ''),
        String(port.oper_status ?? ''),
        action,
        String(deviceCount),
        sampleNames
      ]);
    }
  });

  const now = new Date().toISOString();
  const header = `# Generated by ${GENERATOR.tool} (${verb} — review audit) on ${now}\n`
    + `# Author: ${GENERATOR.author} — ${GENERATOR.url}\n`
    + (batchId ? `# Batch: ${batchId}\n` : '');

  return header + rows.map((r) => r.map(csvEscape).join(',')).join('\n');
}

export function auditCsvFilename(batchId, toolMode) {
  const stem = batchId || 'audit';
  const suffix = toolMode === 'add' ? '-add' : '';
  return `${stem}${suffix}-review.csv`;
}

function csvEscape(v) {
  const s = String(v ?? '');
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}
