#!/usr/bin/env node
// FMN-96: codegen entrypoint. Reads the schema-discovery OpenAPI artifact,
// emits per-domain JS modules under extension/src/lib/claude-tools/codegen/.
//
// Output is committed (not built at runtime) so the extension service worker
// doesn't need a build step. Determinism matters - identical inputs MUST
// produce byte-identical output to keep Anthropic's prompt cache (FMN-66)
// from invalidating on every codegen run.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileToolsByDomain, renderDomainModule } from './derive-tool.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');

// schema-discovery is a sibling project; assume the operator's local
// checkout is at ~/Projects/fortimonitor-schema-discovery. Override via
// FMN_OPENAPI env var if needed.
const DEFAULT_OPENAPI = path.resolve(
  process.env.HOME || '',
  'Projects/fortimonitor-schema-discovery/data/compiled/openapi.json'
);
const OPENAPI_PATH = process.env.FMN_OPENAPI || DEFAULT_OPENAPI;
const OUTPUT_DIR = path.join(REPO_ROOT, 'extension', 'src', 'lib', 'claude-tools', 'codegen');

function main() {
  if (!fs.existsSync(OPENAPI_PATH)) {
    console.error(`OpenAPI artifact not found: ${OPENAPI_PATH}`);
    console.error('Set FMN_OPENAPI=/path/to/openapi.json or check out');
    console.error('  ~/Projects/fortimonitor-schema-discovery (Phases 1-4 complete).');
    process.exit(2);
  }
  console.log(`Reading OpenAPI: ${OPENAPI_PATH}`);
  const spec = JSON.parse(fs.readFileSync(OPENAPI_PATH, 'utf8'));
  console.log(`Paths: ${Object.keys(spec.paths || {}).length}`);

  const byDomain = compileToolsByDomain(spec);
  const domains = Object.keys(byDomain).sort();
  console.log(`Domains: ${domains.length}`);

  if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  // Emit per-domain modules.
  let totalTools = 0;
  for (const d of domains) {
    const tools = byDomain[d];
    totalTools += tools.length;
    const out = path.join(OUTPUT_DIR, `${d}.js`);
    fs.writeFileSync(out, renderDomainModule(d, tools));
    console.log(`  ${d}: ${tools.length} tools  ->  ${path.relative(REPO_ROOT, out)}`);
  }

  // Emit an index that re-exports every domain's TOOLS array, so
  // consumers can pull everything with one import. Tier filtering still
  // happens at the caller level via the tool's `tier` field.
  const indexLines = [
    '// AUTO-GENERATED by tools/codegen/run.mjs - do not edit by hand.',
    '// Re-exports every codegen domain module under a stable name.',
    '',
  ];
  const importLines = [];
  const collectLines = ['export const ALL_CODEGEN_TOOLS = ['];
  for (const d of domains) {
    const ident = `${camel(d)}Tools`;
    importLines.push(`import { TOOLS as ${ident} } from './${d}.js';`);
    collectLines.push(`  ...${ident},`);
  }
  collectLines.push('];');
  const index = indexLines.concat(importLines, [''], collectLines, ['']).join('\n');
  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.js'), index);

  console.log(`\nTotal tools emitted: ${totalTools}`);
  console.log(`Index: ${path.relative(REPO_ROOT, path.join(OUTPUT_DIR, 'index.js'))}`);
}

function camel(snake) {
  return snake.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

main();
