// Unofficial FortiMonitor Toolkit - Gregori Jenkins <https://www.linkedin.com/in/gregorijenkins>
// Markdown runbook generator for the SSO Configuration tool (FMN-139).
// Renders a self-contained "how to set this up on Okta" doc the operator
// can save and share. Deterministic for fixed inputs (no timestamps, no
// random IDs) so the output is diffable and unit-testable.

const DEFAULT_ATTRS = {
  email: 'email',
  firstName: 'firstName',
  lastName: 'lastName',
  groups: 'groups'
};

/**
 * Build the operator-facing Okta admin runbook.
 *
 * Inputs:
 *   spEntityId       - SP entity ID (typically the FortiMonitor base URL)
 *   acsUrl           - Assertion Consumer Service URL
 *   nameIdFormat     - SAML NameID format URN (e.g. emailAddress)
 *   testLoginUrl     - URL the operator visits to test the integration
 *   attributes       - { email, firstName, lastName, groups } SAML attribute names
 *   roleMapping      - { defaultRole: string, overrides: [{ group, role }] }
 *   ssoMode          - 'sso-only' | 'sso-with-password-fallback'
 *   tenantLabel      - human label for this FortiMonitor tenant (display only)
 *   appName          - suggested Okta SAML app name (display only)
 *
 * Returns the Markdown string.
 */
export function buildOktaRunbook({
  spEntityId,
  acsUrl,
  nameIdFormat,
  testLoginUrl = null,
  attributes = {},
  roleMapping = { defaultRole: 'Read-Only', overrides: [] },
  ssoMode = 'sso-with-password-fallback',
  tenantLabel = null,
  appName = 'FortiMonitor'
} = {}) {
  if (!spEntityId) throw new Error('spEntityId is required.');
  if (!acsUrl) throw new Error('acsUrl is required.');
  if (!nameIdFormat) throw new Error('nameIdFormat is required.');

  const attrs = { ...DEFAULT_ATTRS, ...(attributes || {}) };
  const sections = [];

  sections.push(buildHeader({ tenantLabel, appName }));
  sections.push(buildSpValuesSection({ spEntityId, acsUrl, nameIdFormat }));
  sections.push(buildOktaAppSection({ appName, spEntityId, acsUrl, nameIdFormat }));
  sections.push(buildAttributeSection({ attrs }));
  sections.push(buildRoleMappingSection({ roleMapping, attrs }));
  sections.push(buildSsoModeSection({ ssoMode }));
  sections.push(buildTestLoginSection({ testLoginUrl, ssoMode }));
  sections.push(buildTroubleshootingSection({ acsUrl }));

  return sections.join('\n\n') + '\n';
}

function buildHeader({ tenantLabel, appName }) {
  const lines = [`# Okta + FortiMonitor SSO setup runbook`];
  if (tenantLabel) {
    lines.push('');
    lines.push(`Tenant: **${tenantLabel}**  `);
    lines.push(`Okta app: **${appName}**`);
  } else {
    lines.push('');
    lines.push(`Okta app: **${appName}**`);
  }
  lines.push('');
  lines.push('Generated by the Unofficial FortiMonitor Toolkit. Follow the steps top to bottom; each section corresponds to one screen in the Okta admin UI.');
  return lines.join('\n');
}

function buildSpValuesSection({ spEntityId, acsUrl, nameIdFormat }) {
  return [
    '## 1. Values to paste into Okta',
    '',
    'These are the SP-side values FortiMonitor expects. You will paste them into the Okta SAML app config in the next section.',
    '',
    '| Field | Value |',
    '|---|---|',
    `| Audience URI / SP Entity ID | \`${spEntityId}\` |`,
    `| Single sign on URL / ACS URL | \`${acsUrl}\` |`,
    `| Name ID format | \`${nameIdFormat}\` |`,
    `| Application username | \`Email\` (Okta user.email) |`
  ].join('\n');
}

function buildOktaAppSection({ appName, spEntityId, acsUrl, nameIdFormat }) {
  return [
    '## 2. Create the Okta SAML application',
    '',
    '1. Sign in to your Okta admin console as an admin with permission to create applications.',
    '2. Go to **Applications -> Applications -> Create App Integration**.',
    '3. Pick **SAML 2.0** and click **Next**.',
    `4. App name: \`${appName}\`. Click **Next**.`,
    '5. On the **SAML Settings** screen, fill in:',
    `   - **Single sign on URL**: \`${acsUrl}\``,
    '   - Check **Use this for Recipient URL and Destination URL**',
    `   - **Audience URI (SP Entity ID)**: \`${spEntityId}\``,
    `   - **Name ID format**: select the option matching \`${nameIdFormat}\` (typically *EmailAddress*).`,
    '   - **Application username**: **Email**.',
    '',
    'Leave the rest at default for now; the next section adds attribute statements before you save.'
  ].join('\n');
}

function buildAttributeSection({ attrs }) {
  return [
    '## 3. Attribute statements',
    '',
    'Still on the SAML Settings screen, add the following **Attribute Statements**. These are what Okta sends in the SAML assertion; FortiMonitor reads them to populate user records.',
    '',
    '| Name | Name format | Value |',
    '|---|---|---|',
    `| \`${attrs.email}\` | Basic | \`user.email\` |`,
    `| \`${attrs.firstName}\` | Basic | \`user.firstName\` |`,
    `| \`${attrs.lastName}\` | Basic | \`user.lastName\` |`,
    '',
    '### Group attribute statement',
    '',
    'Add one **Group Attribute Statement** so role mapping works:',
    '',
    '| Name | Name format | Filter |',
    '|---|---|---|',
    `| \`${attrs.groups}\` | Basic | Matches regex: \`.*\` (or narrow to specific group prefixes) |`,
    '',
    'A `.*` regex sends every group the user is in. If your Okta tenant has many unrelated groups, narrow to the prefix you use for FortiMonitor access (e.g. `^FortiMonitor-.*`).',
    '',
    'Click **Next** then **Finish** to save the app.'
  ].join('\n');
}

function buildRoleMappingSection({ roleMapping, attrs }) {
  const lines = [
    '## 4. Role mapping',
    '',
    `By default every signed-in Okta user lands in FortiMonitor as **${roleMapping.defaultRole}**.`
  ];

  const overrides = Array.isArray(roleMapping.overrides) ? roleMapping.overrides : [];
  if (overrides.length) {
    lines.push('');
    lines.push('Group-based overrides (highest priority match wins):');
    lines.push('');
    lines.push('| Okta group | FortiMonitor role |');
    lines.push('|---|---|');
    for (const o of overrides) {
      lines.push(`| \`${o.group}\` | \`${o.role}\` |`);
    }
    lines.push('');
    lines.push(`These overrides require the \`${attrs.groups}\` attribute statement from the previous section. Users not in any listed group fall back to **${roleMapping.defaultRole}**.`);
  } else {
    lines.push('');
    lines.push('No per-group overrides configured. Add them later in the FortiMonitor admin UI if you need finer-grained role assignment.');
  }

  return lines.join('\n');
}

function buildSsoModeSection({ ssoMode }) {
  if (ssoMode === 'sso-only') {
    return [
      '## 5. SSO mode',
      '',
      '**SSO-only.** Local password login is disabled. Every user (including admins) must authenticate through Okta.',
      '',
      '> **Lockout warning.** Verify the integration end-to-end with at least one admin account before turning off password login. If Okta SAML breaks, no one can sign in.'
    ].join('\n');
  }
  return [
    '## 5. SSO mode',
    '',
    '**SSO with password fallback.** Users can sign in with either Okta SAML or a local FortiMonitor password. Recommended during cutover; tighten to SSO-only once the integration has been stable for a week.'
  ].join('\n');
}

function buildTestLoginSection({ testLoginUrl, ssoMode }) {
  const lines = ['## 6. Test the integration', ''];
  if (testLoginUrl) {
    lines.push(`1. Open a private/incognito window and visit: ${testLoginUrl}`);
  } else {
    lines.push('1. Open a private/incognito window and visit your FortiMonitor login URL.');
  }
  lines.push('2. Click the SSO option; you should land on Okta.');
  lines.push('3. Authenticate as a user assigned to the new SAML app.');
  lines.push('4. Confirm you land back in FortiMonitor with the expected role.');
  if (ssoMode === 'sso-only') {
    lines.push('5. **Before flipping SSO-only on**: re-test from a different browser profile to confirm a non-cached path works too.');
  }
  return lines.join('\n');
}

function buildTroubleshootingSection({ acsUrl }) {
  return [
    '## 7. Troubleshooting',
    '',
    '- **Browser shows the Okta login then redirects back to Okta on success**: ACS URL mismatch. Re-paste the ACS value above into Okta exactly; trailing slashes matter.',
    '- **FortiMonitor shows "user not provisioned"**: the email attribute is not arriving. Re-check the attribute statement names match what FortiMonitor expects.',
    '- **User lands as Read-Only despite group override**: the group attribute statement is missing or filtering too narrowly. Verify the regex matches the group name in Okta (case sensitive).',
    `- **Signature verification failure**: Okta rotated its signing cert. Re-run this tool with the latest Okta metadata XML and re-save FortiMonitor's SSO config.`,
    '',
    `If the issue persists, capture the full SAML response from your browser's network tab (POST to \`${acsUrl}\`) and decode the base64 \`SAMLResponse\` form field for inspection.`
  ].join('\n');
}
