import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildAuditCsv, auditCsvFilename } from '../src/ui/steps/audit-csv.js';

function sampleGroup(fingerprint, deviceIds, ports) {
  return {
    fingerprint,
    portsData: { ports },
    devices: deviceIds.map((serverId) => ({ serverId }))
  };
}

// --- structural assertions ---------------------------------------

test('audit CSV includes attribution header and both section markers', () => {
  const groups = [sampleGroup('fp1', [1], [{ name: 'wan2', admin_status: 'up', oper_status: 'down', isActive: true }])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove', batchId: 'b1' });
  assert.match(csv, /^# Generated by Unofficial FortiMonitor Toolkit/m);
  assert.match(csv, /^# Author: /m);
  assert.match(csv, /^# Batch: b1$/m);
  assert.match(csv, /^# Section 1: Group Summary$/m);
  assert.match(csv, /^# Section 2: Per-Group Detail$/m);
});

test('audit CSV summary section has one row per group with the expected columns', () => {
  const groups = [
    sampleGroup('fpA', [1, 2], [
      { name: 'wan2', admin_status: 'up', oper_status: 'down', isActive: true },
      { name: 'port1', admin_status: 'up', oper_status: 'up', isActive: true }
    ]),
    sampleGroup('fpB', [10], [
      { name: 'wan1', admin_status: 'up', oper_status: 'up', isActive: true }
    ])
  ];
  const decisions = new Map([['fpA', { skipped: false, removePortNames: ['wan2'] }]]);
  const csv = buildAuditCsv({ groups, decisions, nameById: {}, toolMode: 'remove' });
  // Summary header
  assert.match(csv, /^group_number,group_fingerprint,device_count,port_count_per_device,proposed_action,operator_decision,ports_marked$/m);
  // Summary rows — all admin_status=up so proposal is keep-all; operator_decision carries the user's choice
  assert.match(csv, /^1,fpA,2,2,keep-all,remove: wan2,wan2$/m);
  assert.match(csv, /^2,fpB,1,1,keep-all,undecided,$/m);
});

test('operator_decision with multiple marked ports gets CSV-quoted because of the embedded comma', () => {
  const groups = [sampleGroup('fp1', [1], [
    { name: 'wan1', admin_status: 'up', oper_status: 'up', isActive: true },
    { name: 'wan2', admin_status: 'up', oper_status: 'up', isActive: true },
    { name: 'wan3', admin_status: 'up', oper_status: 'up', isActive: true }
  ])];
  const decisions = new Map([['fp1', { skipped: false, removePortNames: ['wan1', 'wan2'] }]]);
  const csv = buildAuditCsv({ groups, decisions, nameById: {}, toolMode: 'remove' });
  assert.match(csv, /^1,fp1,1,3,keep-all,"remove: wan1, wan2",wan1\|wan2$/m);
});

test('group proposed_action lists ports with admin_status=down (quoted when multi-port)', () => {
  const groups = [sampleGroup('fp1', [1], [
    { name: 'wan1', admin_status: 'down', oper_status: 'down', isActive: true },
    { name: 'wan2', admin_status: 'down', oper_status: 'up', isActive: true },
    { name: 'wan3', admin_status: 'up', oper_status: 'up', isActive: true }
  ])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  assert.match(csv, /^1,fp1,1,3,"remove: wan1, wan2",undecided,$/m);
});

test('group proposed_action is "unknown" when every port has unknown admin_status', () => {
  const groups = [sampleGroup('fp1', [1], [
    { name: 'wan1', admin_status: 'Unknown', oper_status: 'Unknown', isActive: true },
    { name: 'wan2', admin_status: '', oper_status: '', isActive: true }
  ])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  assert.match(csv, /^1,fp1,1,2,unknown,undecided,$/m);
});

test('add mode group proposed_action is "add: ..." for admin-up ports and "skip-all" when none qualify', () => {
  const groups = [
    sampleGroup('fp-candidates', [1], [
      { name: 'wan1', admin_status: 'up', oper_status: 'down', isActive: true },
      { name: 'wan2', admin_status: 'down', oper_status: 'down', isActive: true }
    ]),
    sampleGroup('fp-none', [2], [
      { name: 'wan3', admin_status: 'down', oper_status: 'down', isActive: true }
    ])
  ];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'add' });
  assert.match(csv, /^1,fp-candidates,1,2,add: wan1,undecided,$/m);
  assert.match(csv, /^2,fp-none,1,1,skip-all,undecided,$/m);
});

// --- sort order --------------------------------------------------

test('groups are sorted by descending device_count in both sections, preserving original group_number', () => {
  const groups = [
    sampleGroup('small', [1], [{ name: 'a', admin_status: 'up', oper_status: 'up', isActive: true }]),
    sampleGroup('big', [10, 11, 12, 13], [{ name: 'a', admin_status: 'up', oper_status: 'up', isActive: true }]),
    sampleGroup('mid', [5, 6], [{ name: 'a', admin_status: 'up', oper_status: 'up', isActive: true }])
  ];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  // Extract just the summary-section rows (between Section 1 and Section 2 markers).
  const allLines = csv.split('\n');
  const s1Idx = allLines.findIndex((l) => l === '# Section 1: Group Summary');
  const s2Idx = allLines.findIndex((l) => l === '# Section 2: Per-Group Detail');
  const summaryLines = allLines.slice(s1Idx + 1, s2Idx).filter((l) => /^\d+,[a-z]+,\d+,\d+,/.test(l));
  assert.equal(summaryLines.length, 3);
  assert.match(summaryLines[0], /^2,big,4,/);
  assert.match(summaryLines[1], /^3,mid,2,/);
  assert.match(summaryLines[2], /^1,small,1,/);
  // Detail section headers appear in the same order
  const detailHeaders = csv.split('\n').filter((l) => l.startsWith('# Group '));
  assert.match(detailHeaders[0], /^# Group 2 of 3 — fingerprint=big/);
  assert.match(detailHeaders[1], /^# Group 3 of 3 — fingerprint=mid/);
  assert.match(detailHeaders[2], /^# Group 1 of 3 — fingerprint=small/);
});

// --- per-port proposed_action --------------------------------------

test('per-port operator_decision reflects the decision: remove/add/keep/skipped/undecided', () => {
  const groups = [
    sampleGroup('fp-remove', [1], [
      { name: 'wan2', admin_status: 'up', oper_status: 'down', isActive: true },
      { name: 'port1', admin_status: 'up', oper_status: 'up', isActive: true }
    ]),
    sampleGroup('fp-add', [2], [
      { name: 'wan2', admin_status: 'up', oper_status: 'down', isActive: false }
    ]),
    sampleGroup('fp-skipped', [3], [
      { name: 'wan2', admin_status: 'up', oper_status: 'up', isActive: true }
    ]),
    sampleGroup('fp-undecided', [4], [
      { name: 'wan2', admin_status: 'up', oper_status: 'up', isActive: true }
    ])
  ];
  const removeDecisions = new Map([
    ['fp-remove', { skipped: false, removePortNames: ['wan2'] }],
    ['fp-skipped', { skipped: true, removePortNames: [] }]
  ]);
  const csvRemove = buildAuditCsv({ groups: [groups[0], groups[2], groups[3]], decisions: removeDecisions, nameById: {}, toolMode: 'remove' });
  // Columns: port_name,admin_status,oper_status,is_active,proposed_action,operator_decision
  // admin_status=up in remove mode → proposed=keep for every port in this test
  assert.match(csvRemove, /^wan2,up,down,yes,keep,remove$/m);
  assert.match(csvRemove, /^port1,up,up,yes,keep,keep$/m);
  assert.match(csvRemove, /^wan2,up,up,yes,keep,skipped$/m);
  assert.match(csvRemove, /^wan2,up,up,yes,keep,undecided$/m);

  const addDecisions = new Map([['fp-add', { skipped: false, addPortNames: ['wan2'] }]]);
  const csvAdd = buildAuditCsv({ groups: [groups[1]], decisions: addDecisions, nameById: {}, toolMode: 'add' });
  // admin_status=up in add mode → proposed=add
  assert.match(csvAdd, /^wan2,up,down,no,add,add$/m);
});

test('per-port proposed_action is derived from admin_status (remove mode)', () => {
  const groups = [sampleGroup('fp1', [1], [
    { name: 'a', admin_status: 'down', oper_status: 'down', isActive: true },
    { name: 'b', admin_status: 'up', oper_status: 'down', isActive: true },
    { name: 'c', admin_status: 'Unknown', oper_status: 'Unknown', isActive: true }
  ])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  assert.match(csv, /^a,down,down,yes,remove,undecided$/m);
  assert.match(csv, /^b,up,down,yes,keep,undecided$/m);
  assert.match(csv, /^c,Unknown,Unknown,yes,unknown,undecided$/m);
});

test('per-port proposed_action is derived from admin_status (add mode)', () => {
  const groups = [sampleGroup('fp1', [1], [
    { name: 'a', admin_status: 'up', oper_status: 'down', isActive: true },
    { name: 'b', admin_status: 'down', oper_status: 'down', isActive: true },
    { name: 'c', admin_status: '', oper_status: '', isActive: true }
  ])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'add' });
  assert.match(csv, /^a,up,down,yes,add,undecided$/m);
  assert.match(csv, /^b,down,down,yes,skip,undecided$/m);
  assert.match(csv, /^c,,,yes,unknown,undecided$/m);
});

test('proposed_action ignores admin_status case (UP/DOWN match lowercase up/down)', () => {
  const groups = [sampleGroup('fp1', [1], [
    { name: 'a', admin_status: 'UP', oper_status: 'up', isActive: true },
    { name: 'b', admin_status: 'Down', oper_status: 'down', isActive: true }
  ])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  assert.match(csv, /^a,UP,up,yes,keep,undecided$/m);
  assert.match(csv, /^b,Down,down,yes,remove,undecided$/m);
});

// --- is_active rendering ------------------------------------------

test('is_active renders as yes/no for truthy/falsy values', () => {
  const groups = [sampleGroup('fp1', [1], [
    { name: 'a', admin_status: 'up', oper_status: 'up', isActive: true },
    { name: 'b', admin_status: 'up', oper_status: 'up', isActive: false }
  ])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  assert.match(csv, /^a,up,up,yes,keep,undecided$/m);
  assert.match(csv, /^b,up,up,no,keep,undecided$/m);
});

// --- device list -------------------------------------------------

test('device rows list every device in the group (no 20-device truncation)', () => {
  const deviceIds = Array.from({ length: 25 }, (_, i) => 1000 + i);
  const groups = [sampleGroup('fp1', deviceIds, [{ name: 'wan2', admin_status: 'up', oper_status: 'up', isActive: true }])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  // Count device rows: lines that look like "1000,..." through "1024,..."
  const deviceRows = csv.split('\n').filter((l) => /^10\d\d,/.test(l));
  assert.equal(deviceRows.length, 25);
  // First and last devices present
  assert.match(csv, /^1000,1000$/m);
  assert.match(csv, /^1024,1024$/m);
});

test('device_name resolves from nameById and falls back to serverId', () => {
  const groups = [sampleGroup('fp1', [100, 101], [{ name: 'wan2', admin_status: 'up', oper_status: 'up', isActive: true }])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: { '100': 'FGT-Branch-A' }, toolMode: 'remove' });
  assert.match(csv, /^100,FGT-Branch-A$/m);
  assert.match(csv, /^101,101$/m);
});

// --- edge cases --------------------------------------------------

test('admin_status and oper_status are preserved verbatim (including "Unknown")', () => {
  const groups = [sampleGroup('fp1', [1], [
    { name: 'wan2', admin_status: 'Unknown', oper_status: 'Unknown', isActive: true }
  ])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  // Unknown admin_status → proposed_action=unknown; no decision → operator_decision=undecided
  assert.match(csv, /^wan2,Unknown,Unknown,yes,unknown,undecided$/m);
});

test('ports_marked summary field is empty for skipped/undecided groups', () => {
  const groups = [
    sampleGroup('fp-skipped', [1], [{ name: 'wan2', admin_status: 'up', oper_status: 'up', isActive: true }]),
    sampleGroup('fp-undecided', [2], [{ name: 'wan2', admin_status: 'up', oper_status: 'up', isActive: true }])
  ];
  const decisions = new Map([['fp-skipped', { skipped: true, removePortNames: [] }]]);
  const csv = buildAuditCsv({ groups, decisions, nameById: {}, toolMode: 'remove' });
  // admin_status=up → proposed_action=keep-all; operator_decision carries skipped/undecided
  assert.match(csv, /^1,fp-skipped,1,1,keep-all,skipped,$/m);
  assert.match(csv, /^2,fp-undecided,1,1,keep-all,undecided,$/m);
});

test('empty groups list produces a valid CSV with both section markers', () => {
  const csv = buildAuditCsv({ groups: [], decisions: new Map(), nameById: {}, toolMode: 'remove' });
  assert.match(csv, /Section 1: Group Summary/);
  assert.match(csv, /Section 2: Per-Group Detail/);
  assert.match(csv, /^group_number,group_fingerprint,/m);
});

// --- filename ----------------------------------------------------

test('auditCsvFilename includes batch id and mode suffix', () => {
  assert.equal(auditCsvFilename('b123', 'remove'), 'b123-review.csv');
  assert.equal(auditCsvFilename('b123', 'add'), 'b123-add-review.csv');
  assert.equal(auditCsvFilename('', 'remove'), 'audit-review.csv');
});
