import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildAuditCsv, auditCsvFilename } from '../src/ui/steps/audit-csv.js';

function sampleGroup(fingerprint, deviceIds, ports) {
  return {
    fingerprint,
    portsData: { ports },
    devices: deviceIds.map((serverId) => ({ serverId }))
  };
}

test('audit CSV has one row per (group, port) plus attribution header and column header', () => {
  const groups = [
    sampleGroup('fp1', [1, 2, 3], [
      { name: 'wan2', admin_status: 'up', oper_status: 'down' },
      { name: 'port1', admin_status: 'up', oper_status: 'up' }
    ]),
    sampleGroup('fp2', [10], [
      { name: 'wan1', admin_status: 'down', oper_status: 'down' }
    ])
  ];
  const decisions = new Map([
    ['fp1', { skipped: false, removePortNames: ['wan2'] }]
  ]);
  const csv = buildAuditCsv({ groups, decisions, nameById: {}, toolMode: 'remove', batchId: 'b1' });
  const lines = csv.split('\n');
  assert.ok(lines[0].startsWith('# Generated by'));
  assert.ok(lines.some((l) => l.startsWith('# Batch: b1')));
  const headerIdx = lines.findIndex((l) => l.startsWith('group_number,'));
  assert.notEqual(headerIdx, -1);
  const dataLines = lines.slice(headerIdx + 1);
  assert.equal(dataLines.length, 3);
});

test('audit CSV marks ports in a group with decision: remove vs keep vs undecided', () => {
  const groups = [
    sampleGroup('fp1', [1], [
      { name: 'wan2', admin_status: 'up', oper_status: 'down' },
      { name: 'port1', admin_status: 'up', oper_status: 'up' }
    ]),
    sampleGroup('fp2', [2], [
      { name: 'wan1', admin_status: 'up', oper_status: 'down' }
    ])
  ];
  const decisions = new Map([
    ['fp1', { skipped: false, removePortNames: ['wan2'] }]
  ]);
  const csv = buildAuditCsv({ groups, decisions, nameById: {}, toolMode: 'remove' });
  assert.match(csv, /,wan2,up,down,remove,/);
  assert.match(csv, /,port1,up,up,keep,/);
  assert.match(csv, /,wan1,up,down,undecided,/);
});

test('audit CSV marks skipped groups', () => {
  const groups = [
    sampleGroup('fp1', [1], [{ name: 'wan2', admin_status: 'up', oper_status: 'down' }])
  ];
  const decisions = new Map([
    ['fp1', { skipped: true, removePortNames: [] }]
  ]);
  const csv = buildAuditCsv({ groups, decisions, nameById: {}, toolMode: 'remove' });
  assert.match(csv, /,skipped,/);
});

test('audit CSV uses "add" verb when toolMode is add', () => {
  const groups = [
    sampleGroup('fp1', [1], [
      { name: 'port5', admin_status: 'up', oper_status: 'up' }
    ])
  ];
  const decisions = new Map([
    ['fp1', { skipped: false, addPortNames: ['port5'] }]
  ]);
  const csv = buildAuditCsv({ groups, decisions, nameById: {}, toolMode: 'add' });
  assert.match(csv, /,port5,up,up,add,/);
});

test('audit CSV sample_device_names resolves names from nameById', () => {
  const groups = [
    sampleGroup('fp1', [100, 101], [
      { name: 'wan2', admin_status: 'up', oper_status: 'down' }
    ])
  ];
  const decisions = new Map();
  const nameById = { '100': 'FGT-Branch-A', '101': 'FGT-Branch-B' };
  const csv = buildAuditCsv({ groups, decisions, nameById, toolMode: 'remove' });
  assert.match(csv, /FGT-Branch-A\|FGT-Branch-B/);
});

test('audit CSV falls back to server_id when name not in nameById', () => {
  const groups = [
    sampleGroup('fp1', [100], [{ name: 'wan2', admin_status: 'up', oper_status: 'down' }])
  ];
  const decisions = new Map();
  const csv = buildAuditCsv({ groups, decisions, nameById: {}, toolMode: 'remove' });
  assert.match(csv, /,1,100/);
});

test('audit CSV truncates device sample to 20 with + more suffix', () => {
  const deviceIds = Array.from({ length: 25 }, (_, i) => i + 1);
  const groups = [sampleGroup('fp1', deviceIds, [{ name: 'wan2', admin_status: 'up', oper_status: 'down' }])];
  const csv = buildAuditCsv({ groups, decisions: new Map(), nameById: {}, toolMode: 'remove' });
  assert.match(csv, /\|\+5 more/);
});

test('auditCsvFilename includes batch id and mode suffix', () => {
  assert.equal(auditCsvFilename('b123', 'remove'), 'b123-review.csv');
  assert.equal(auditCsvFilename('b123', 'add'), 'b123-add-review.csv');
  assert.equal(auditCsvFilename('', 'remove'), 'audit-review.csv');
});
